# Form implementation generated from reading ui file 'applicantDash.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicantDash(object):
    def setupUi(self, ApplicantDash):
        ApplicantDash.setObjectName("ApplicantDash")
        ApplicantDash.resize(1017, 756)
        ApplicantDash.setStyleSheet("background-color: rgb(20, 41, 63);")
        self.centralwidget = QtWidgets.QWidget(parent=ApplicantDash)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.headerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.headerWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(6, 57, 112);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border: 2px solid;\n"
"    border-color: black;\n"
"    border-radius: 10px;\n"
"    \n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuBtn = QtWidgets.QPushButton(parent=self.headerWidget)
        self.menuBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.menuBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.menuBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuBtn.setIcon(icon)
        self.menuBtn.setCheckable(True)
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_4.addWidget(self.menuBtn)
        spacerItem = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBarTxt = QtWidgets.QLineEdit(parent=self.headerWidget)
        self.searchBarTxt.setObjectName("searchBarTxt")
        self.horizontalLayout.addWidget(self.searchBarTxt)
        self.searchBtn = QtWidgets.QPushButton(parent=self.headerWidget)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.searchBtn.setStyleSheet("QPushButton:checked{\n"
"    border: none;\n"
"    \n"
"}")
        self.searchBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchBtn.setIcon(icon1)
        self.searchBtn.setCheckable(True)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.profileBtnQuickAccess = QtWidgets.QPushButton(parent=self.headerWidget)
        self.profileBtnQuickAccess.setMinimumSize(QtCore.QSize(40, 40))
        self.profileBtnQuickAccess.setMaximumSize(QtCore.QSize(40, 40))
        self.profileBtnQuickAccess.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.profileBtnQuickAccess.setStyleSheet("")
        self.profileBtnQuickAccess.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profileBtnQuickAccess.setIcon(icon2)
        self.profileBtnQuickAccess.setCheckable(True)
        self.profileBtnQuickAccess.setAutoExclusive(True)
        self.profileBtnQuickAccess.setObjectName("profileBtnQuickAccess")
        self.horizontalLayout_4.addWidget(self.profileBtnQuickAccess)
        self.gridLayout.addWidget(self.headerWidget, 0, 2, 1, 1)
        self.iconNameWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconNameWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(11, 100, 197);\n"
"    width:200px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(1, 14, 27);\n"
"    font: 12pt \"Yu Gothic UI\";\n"
"    text-align: left;\n"
"    height:40px;\n"
"    border:none;\n"
"    padding:7px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(1, 14, 27);\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"    \n"
"    background-color: rgb(20, 41, 63);\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    padding-right:10px;\n"
"}")
        self.iconNameWidget.setObjectName("iconNameWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.iconNameWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 5, 0, 17)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.fullNavIcon = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.fullNavIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.fullNavIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.fullNavIcon.setText("")
        self.fullNavIcon.setPixmap(QtGui.QPixmap(":/icons/SMsysIcon.png"))
        self.fullNavIcon.setScaledContents(True)
        self.fullNavIcon.setObjectName("fullNavIcon")
        self.gridLayout_6.addWidget(self.fullNavIcon, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomeLabel = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.verticalLayout.addWidget(self.welcomeLabel)
        self.usernameLabel = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icons/whiteHomeIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.homeBtn.setIcon(icon3)
        self.homeBtn.setCheckable(True)
        self.homeBtn.setAutoExclusive(True)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_2.addWidget(self.homeBtn)
        self.scholarshipBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.scholarshipBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/manageScholarship.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icons/whiteManageScholarshipIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.scholarshipBtn.setIcon(icon4)
        self.scholarshipBtn.setCheckable(True)
        self.scholarshipBtn.setAutoExclusive(True)
        self.scholarshipBtn.setObjectName("scholarshipBtn")
        self.verticalLayout_2.addWidget(self.scholarshipBtn)
        self.reportBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.reportBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/report.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icons/graph.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.reportBtn.setIcon(icon5)
        self.reportBtn.setCheckable(True)
        self.reportBtn.setAutoExclusive(True)
        self.reportBtn.setObjectName("reportBtn")
        self.verticalLayout_2.addWidget(self.reportBtn)
        self.reportLogsBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/history.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icons/historyWhite.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.reportLogsBtn.setIcon(icon6)
        self.reportLogsBtn.setCheckable(True)
        self.reportLogsBtn.setAutoExclusive(True)
        self.reportLogsBtn.setObjectName("reportLogsBtn")
        self.verticalLayout_2.addWidget(self.reportLogsBtn)
        self.notificationsBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.notificationsBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/notification.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icons/alarm-bell.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.notificationsBtn.setIcon(icon7)
        self.notificationsBtn.setCheckable(True)
        self.notificationsBtn.setAutoExclusive(True)
        self.notificationsBtn.setObjectName("notificationsBtn")
        self.verticalLayout_2.addWidget(self.notificationsBtn)
        self.profileBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.profileBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/settings (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.profileBtn.setIcon(icon8)
        self.profileBtn.setCheckable(True)
        self.profileBtn.setAutoExclusive(True)
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_2.addWidget(self.profileBtn)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 209, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.logoutBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/powerBTN.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoutBtn.setIcon(icon9)
        self.logoutBtn.setCheckable(True)
        self.logoutBtn.setAutoExclusive(True)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_4.addWidget(self.logoutBtn)
        self.gridLayout.addWidget(self.iconNameWidget, 0, 1, 2, 1)
        self.mainDisplayWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.mainDisplayWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(6, 57, 112);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 700 16pt \"Segoe UI\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding: 17px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:20px;\n"
"    margin-left:20px;\n"
"    \n"
"    font: 600 10.5pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(20, 41, 63);\n"
"    color: Black;\n"
"}\n"
"")
        self.mainDisplayWidget.setObjectName("mainDisplayWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.home)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 408, 320))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.homeScreenUsernameLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.homeScreenUsernameLabel.setObjectName("homeScreenUsernameLabel")
        self.horizontalLayout_5.addWidget(self.homeScreenUsernameLabel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(20, 0, 20, 20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mostCommonSchemesChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.mostCommonSchemesChart.setObjectName("mostCommonSchemesChart")
        self.verticalLayout_8.addWidget(self.mostCommonSchemesChart)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.totalNumberOfApplicantsLabelHome = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.totalNumberOfApplicantsLabelHome.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.totalNumberOfApplicantsLabelHome.setObjectName("totalNumberOfApplicantsLabelHome")
        self.verticalLayout_7.addWidget(self.totalNumberOfApplicantsLabelHome)
        self.totalNumOfScholarshipsLabelHome = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.totalNumOfScholarshipsLabelHome.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.totalNumOfScholarshipsLabelHome.setObjectName("totalNumOfScholarshipsLabelHome")
        self.verticalLayout_7.addWidget(self.totalNumOfScholarshipsLabelHome)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.gridLayout_7.addLayout(self.verticalLayout_8, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(20, -1, 20, 20)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chartWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.chartWidget.setObjectName("chartWidget")
        self.horizontalLayout_7.addWidget(self.chartWidget)
        self.chart2Widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_2)
        self.chart2Widget.setObjectName("chart2Widget")
        self.horizontalLayout_7.addWidget(self.chart2Widget)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.chart1Label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.chart1Label.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.chart1Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chart1Label.setObjectName("chart1Label")
        self.horizontalLayout_2.addWidget(self.chart1Label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.chart2Label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.chart2Label.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.chart2Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.chart2Label.setObjectName("chart2Label")
        self.horizontalLayout_2.addWidget(self.chart2Label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.changeChartBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_2)
        self.changeChartBtn.setObjectName("changeChartBtn")
        self.gridLayout_7.addWidget(self.changeChartBtn, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.mainDisplayWidget.addWidget(self.home)
        self.manageScholarships = QtWidgets.QWidget()
        self.manageScholarships.setObjectName("manageScholarships")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.manageScholarships)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(20, -1, 20, 40)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(parent=self.manageScholarships)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.customScholarshipLabel = QtWidgets.QLabel(parent=self.manageScholarships)
        self.customScholarshipLabel.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.customScholarshipLabel.setText("")
        self.customScholarshipLabel.setObjectName("customScholarshipLabel")
        self.verticalLayout_10.addWidget(self.customScholarshipLabel)
        self.scholarshipTableWidget = QtWidgets.QTableWidget(parent=self.manageScholarships)
        self.scholarshipTableWidget.setStyleSheet("color: rgb(1, 14, 27);")
        self.scholarshipTableWidget.setObjectName("scholarshipTableWidget")
        self.scholarshipTableWidget.setColumnCount(0)
        self.scholarshipTableWidget.setRowCount(0)
        self.verticalLayout_10.addWidget(self.scholarshipTableWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.mainDisplayWidget.addWidget(self.manageScholarships)
        self.report = QtWidgets.QWidget()
        self.report.setObjectName("report")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.report)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.report)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 709, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 2, 1, 3)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(15)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_21 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_21.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_28.addWidget(self.label_21)
        self.financialAmountPerScholarshipChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.financialAmountPerScholarshipChart.setObjectName("financialAmountPerScholarshipChart")
        self.verticalLayout_28.addWidget(self.financialAmountPerScholarshipChart)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setSpacing(15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_13 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_23.addWidget(self.label_13)
        self.mostAppliedScholarshipsChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.mostAppliedScholarshipsChart.setStyleSheet("border-radius: 7px;")
        self.mostAppliedScholarshipsChart.setObjectName("mostAppliedScholarshipsChart")
        self.verticalLayout_23.addWidget(self.mostAppliedScholarshipsChart)
        self.verticalLayout_28.addLayout(self.verticalLayout_23)
        self.gridLayout_5.addLayout(self.verticalLayout_28, 9, 4, 1, 3)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(15)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_18.addWidget(self.label_4)
        self.applicantsPerCountryChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.applicantsPerCountryChart.setStyleSheet("border-radius: 7px;")
        self.applicantsPerCountryChart.setObjectName("applicantsPerCountryChart")
        self.verticalLayout_18.addWidget(self.applicantsPerCountryChart)
        self.gridLayout_5.addLayout(self.verticalLayout_18, 4, 0, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(221, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 8, 6, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_19.addWidget(self.label_9)
        self.commonProgramsTableWidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.commonProgramsTableWidget.setStyleSheet("color:black;")
        self.commonProgramsTableWidget.setObjectName("commonProgramsTableWidget")
        self.commonProgramsTableWidget.setColumnCount(0)
        self.commonProgramsTableWidget.setRowCount(0)
        self.verticalLayout_19.addWidget(self.commonProgramsTableWidget)
        self.mostCommonProgram = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.mostCommonProgram.setStyleSheet("border-radius: 7px;")
        self.mostCommonProgram.setObjectName("mostCommonProgram")
        self.verticalLayout_19.addWidget(self.mostCommonProgram)
        self.gridLayout_5.addLayout(self.verticalLayout_19, 4, 4, 1, 3)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setSpacing(15)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_21.addWidget(self.label_11)
        self.applicantEducationLevelChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.applicantEducationLevelChart.setStyleSheet("border-radius: 7px;")
        self.applicantEducationLevelChart.setObjectName("applicantEducationLevelChart")
        self.verticalLayout_21.addWidget(self.applicantEducationLevelChart)
        self.gridLayout_5.addLayout(self.verticalLayout_21, 5, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(246, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 7)
        spacerItem11 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem11, 7, 3, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 2, 3, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(246, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem13, 8, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 1, 1, 5)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(15)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        spacerItem14 = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_25.addItem(spacerItem14)
        self.label_18 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_25.addWidget(self.label_18)
        self.schemesAvaliableTableWidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.schemesAvaliableTableWidget.setStyleSheet("color:black;")
        self.schemesAvaliableTableWidget.setObjectName("schemesAvaliableTableWidget")
        self.schemesAvaliableTableWidget.setColumnCount(0)
        self.schemesAvaliableTableWidget.setRowCount(0)
        self.verticalLayout_25.addWidget(self.schemesAvaliableTableWidget)
        self.totalNumOfScholarshipsLabelReports = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.totalNumOfScholarshipsLabelReports.setObjectName("totalNumOfScholarshipsLabelReports")
        self.verticalLayout_25.addWidget(self.totalNumOfScholarshipsLabelReports)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(15)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_15 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_15.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_24.addWidget(self.label_15)
        self.schemeRatioChart = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.schemeRatioChart.setStyleSheet("border-radius: 7px;")
        self.schemeRatioChart.setObjectName("schemeRatioChart")
        self.verticalLayout_24.addWidget(self.schemeRatioChart)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.gridLayout_5.addLayout(self.verticalLayout_25, 9, 0, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(221, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem15, 3, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 6, 0, 1, 7)
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 8, 1, 1, 5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_20.addWidget(self.scrollArea_2)
        self.printReportBtn = QtWidgets.QPushButton(parent=self.report)
        self.printReportBtn.setObjectName("printReportBtn")
        self.verticalLayout_20.addWidget(self.printReportBtn)
        self.mainDisplayWidget.addWidget(self.report)
        self.notificationsPage = QtWidgets.QWidget()
        self.notificationsPage.setObjectName("notificationsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.notificationsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.notificationPageTitleLabel = QtWidgets.QLabel(parent=self.notificationsPage)
        self.notificationPageTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notificationPageTitleLabel.setObjectName("notificationPageTitleLabel")
        self.verticalLayout_6.addWidget(self.notificationPageTitleLabel)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem16)
        self.notiFilterCombo = QtWidgets.QComboBox(parent=self.notificationsPage)
        self.notiFilterCombo.setStyleSheet("width:200px;")
        self.notiFilterCombo.setObjectName("notiFilterCombo")
        self.notiFilterCombo.addItem("")
        self.notiFilterCombo.addItem("")
        self.notiFilterCombo.addItem("")
        self.horizontalLayout_6.addWidget(self.notiFilterCombo)
        self.noftiFilterbtn = QtWidgets.QPushButton(parent=self.notificationsPage)
        self.noftiFilterbtn.setStyleSheet("margin:0px;\n"
"padding:3px;\n"
"background-color: rgb(1, 14, 27);\n"
"height:20px;\n"
"width:70px;\n"
"font: 9pt \"Segoe UI\";\n"
"border-radius:5px;")
        self.noftiFilterbtn.setObjectName("noftiFilterbtn")
        self.horizontalLayout_6.addWidget(self.noftiFilterbtn)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.notificationsTableWidget = QtWidgets.QTableWidget(parent=self.notificationsPage)
        self.notificationsTableWidget.setStyleSheet("margin-left:20px;\n"
"margin-right:20px;\n"
"margin-top:20px;\n"
"margin-bottom:20px;\n"
"color: rgb(1, 14, 27);")
        self.notificationsTableWidget.setObjectName("notificationsTableWidget")
        self.notificationsTableWidget.setColumnCount(0)
        self.notificationsTableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.notificationsTableWidget)
        self.mainDisplayWidget.addWidget(self.notificationsPage)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.profile)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_2 = QtWidgets.QLabel(parent=self.profile)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_17.addWidget(self.label_2)
        self.usenameLabelProfile = QtWidgets.QLabel(parent=self.profile)
        self.usenameLabelProfile.setStyleSheet("font: 600 12pt \"Segoe UI\";")
        self.usenameLabelProfile.setObjectName("usenameLabelProfile")
        self.verticalLayout_17.addWidget(self.usenameLabelProfile)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(parent=self.profile)
        self.label_5.setStyleSheet("font: 600 12pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.usernameTxt = QtWidgets.QLineEdit(parent=self.profile)
        self.usernameTxt.setStyleSheet("margin-bottom:30px;")
        self.usernameTxt.setObjectName("usernameTxt")
        self.horizontalLayout_11.addWidget(self.usernameTxt)
        self.changeUsernameBtn = QtWidgets.QPushButton(parent=self.profile)
        self.changeUsernameBtn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding:10px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:0px;\n"
"    margin-left:0px;\n"
"    \n"
"    font: 600 10pt \"Segoe UI\";\n"
"}")
        self.changeUsernameBtn.setObjectName("changeUsernameBtn")
        self.horizontalLayout_11.addWidget(self.changeUsernameBtn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_17.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_6 = QtWidgets.QLabel(parent=self.profile)
        self.label_6.setStyleSheet("font: 600 12pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.emailTxt = QtWidgets.QLineEdit(parent=self.profile)
        self.emailTxt.setStyleSheet("margin-bottom:30px;")
        self.emailTxt.setObjectName("emailTxt")
        self.horizontalLayout_12.addWidget(self.emailTxt)
        self.changeEmailBtn = QtWidgets.QPushButton(parent=self.profile)
        self.changeEmailBtn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding:10px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:0px;\n"
"    margin-left:0px;\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}")
        self.changeEmailBtn.setObjectName("changeEmailBtn")
        self.horizontalLayout_12.addWidget(self.changeEmailBtn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_12)
        self.verticalLayout_17.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(20, -1, 20, 20)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_7 = QtWidgets.QLabel(parent=self.profile)
        self.label_7.setStyleSheet("font: 600 12pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_15.addWidget(self.label_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.passTxt = QtWidgets.QLineEdit(parent=self.profile)
        self.passTxt.setStyleSheet("margin-bottom:30px;")
        self.passTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt.setObjectName("passTxt")
        self.horizontalLayout_13.addWidget(self.passTxt)
        self.showPassBtn = QtWidgets.QPushButton(parent=self.profile)
        self.showPassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.showPassBtn.setMouseTracking(True)
        self.showPassBtn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding:5px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:0px;\n"
"    margin-left:0px;\n"
"    background-color: rgb(6, 57, 112);\n"
"}")
        self.showPassBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/seeWhiteIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPassBtn.setIcon(icon10)
        self.showPassBtn.setIconSize(QtCore.QSize(20, 20))
        self.showPassBtn.setCheckable(True)
        self.showPassBtn.setObjectName("showPassBtn")
        self.horizontalLayout_13.addWidget(self.showPassBtn)
        self.changePassBtn = QtWidgets.QPushButton(parent=self.profile)
        self.changePassBtn.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding:10px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:0px;\n"
"    margin-left:0px;\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}")
        self.changePassBtn.setObjectName("changePassBtn")
        self.horizontalLayout_13.addWidget(self.changePassBtn)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.dateJoinedLabel = QtWidgets.QLabel(parent=self.profile)
        self.dateJoinedLabel.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"margin-bottom:80px;")
        self.dateJoinedLabel.setObjectName("dateJoinedLabel")
        self.verticalLayout_16.addWidget(self.dateJoinedLabel)
        self.LogoutBtn = QtWidgets.QPushButton(parent=self.profile)
        self.LogoutBtn.setObjectName("LogoutBtn")
        self.verticalLayout_16.addWidget(self.LogoutBtn)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.mainDisplayWidget.addWidget(self.profile)
        self.reportLogs = QtWidgets.QWidget()
        self.reportLogs.setObjectName("reportLogs")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.reportLogs)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(parent=self.reportLogs)
        self.label_3.setStyleSheet("margin-top:30px;")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.reportLogsTableWidget = QtWidgets.QTableWidget(parent=self.reportLogs)
        self.reportLogsTableWidget.setStyleSheet("margin:30px;")
        self.reportLogsTableWidget.setObjectName("reportLogsTableWidget")
        self.reportLogsTableWidget.setColumnCount(0)
        self.reportLogsTableWidget.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.reportLogsTableWidget)
        self.pdfViewerScrollWidget = QtWidgets.QScrollArea(parent=self.reportLogs)
        self.pdfViewerScrollWidget.setWidgetResizable(True)
        self.pdfViewerScrollWidget.setObjectName("pdfViewerScrollWidget")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 567))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_11.addWidget(self.label_12)
        self.pdfViewerScrollWidget.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_8.addWidget(self.pdfViewerScrollWidget)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.mainDisplayWidget.addWidget(self.reportLogs)
        self.gridLayout.addWidget(self.mainDisplayWidget, 1, 2, 1, 1)
        self.iconOnlyWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconOnlyWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(11, 100, 197);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(1, 14, 27);\n"
"    height:40px;\n"
"    border:none;\n"
"    padding:7px;\n"
"}\n"
"")
        self.iconOnlyWidget.setObjectName("iconOnlyWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.iconOnlyWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.smallNavIcon = QtWidgets.QLabel(parent=self.iconOnlyWidget)
        self.smallNavIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.smallNavIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.smallNavIcon.setText("")
        self.smallNavIcon.setPixmap(QtGui.QPixmap(":/icons/SMsysIcon.png"))
        self.smallNavIcon.setScaledContents(True)
        self.smallNavIcon.setObjectName("smallNavIcon")
        self.horizontalLayout_3.addWidget(self.smallNavIcon)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.homeIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.homeIconBtn.setText("")
        self.homeIconBtn.setIcon(icon3)
        self.homeIconBtn.setCheckable(True)
        self.homeIconBtn.setAutoExclusive(True)
        self.homeIconBtn.setObjectName("homeIconBtn")
        self.verticalLayout_3.addWidget(self.homeIconBtn)
        self.scholarshipIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.scholarshipIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.scholarshipIconBtn.setText("")
        self.scholarshipIconBtn.setIcon(icon4)
        self.scholarshipIconBtn.setCheckable(True)
        self.scholarshipIconBtn.setAutoExclusive(True)
        self.scholarshipIconBtn.setObjectName("scholarshipIconBtn")
        self.verticalLayout_3.addWidget(self.scholarshipIconBtn)
        self.reportIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.reportIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.reportIconBtn.setText("")
        self.reportIconBtn.setIcon(icon5)
        self.reportIconBtn.setCheckable(True)
        self.reportIconBtn.setAutoExclusive(True)
        self.reportIconBtn.setObjectName("reportIconBtn")
        self.verticalLayout_3.addWidget(self.reportIconBtn)
        self.reportLogsIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.reportLogsIconBtn.setText("")
        self.reportLogsIconBtn.setIcon(icon6)
        self.reportLogsIconBtn.setCheckable(True)
        self.reportLogsIconBtn.setAutoExclusive(True)
        self.reportLogsIconBtn.setObjectName("reportLogsIconBtn")
        self.verticalLayout_3.addWidget(self.reportLogsIconBtn)
        self.notificationsIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.notificationsIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.notificationsIconBtn.setText("")
        self.notificationsIconBtn.setIcon(icon7)
        self.notificationsIconBtn.setCheckable(True)
        self.notificationsIconBtn.setAutoExclusive(True)
        self.notificationsIconBtn.setObjectName("notificationsIconBtn")
        self.verticalLayout_3.addWidget(self.notificationsIconBtn)
        self.profileIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.profileIconBtn.setText("")
        self.profileIconBtn.setIcon(icon8)
        self.profileIconBtn.setCheckable(True)
        self.profileIconBtn.setAutoExclusive(True)
        self.profileIconBtn.setObjectName("profileIconBtn")
        self.verticalLayout_3.addWidget(self.profileIconBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem18 = QtWidgets.QSpacerItem(20, 203, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem18)
        self.logoutIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.logoutIconBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logoutIconBtn.setText("")
        self.logoutIconBtn.setIcon(icon9)
        self.logoutIconBtn.setCheckable(True)
        self.logoutIconBtn.setAutoExclusive(True)
        self.logoutIconBtn.setObjectName("logoutIconBtn")
        self.verticalLayout_5.addWidget(self.logoutIconBtn)
        self.gridLayout.addWidget(self.iconOnlyWidget, 0, 0, 2, 1)
        ApplicantDash.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ApplicantDash)
        self.statusbar.setObjectName("statusbar")
        ApplicantDash.setStatusBar(self.statusbar)

        self.retranslateUi(ApplicantDash)
        self.mainDisplayWidget.setCurrentIndex(5)
        self.homeBtn.toggled['bool'].connect(self.homeIconBtn.setChecked) # type: ignore
        self.homeIconBtn.toggled['bool'].connect(self.homeBtn.setChecked) # type: ignore
        self.profileBtn.toggled['bool'].connect(self.profileIconBtn.setChecked) # type: ignore
        self.profileIconBtn.toggled['bool'].connect(self.profileBtn.setChecked) # type: ignore
        self.scholarshipIconBtn.toggled['bool'].connect(self.scholarshipBtn.setChecked) # type: ignore
        self.scholarshipBtn.toggled['bool'].connect(self.scholarshipIconBtn.setChecked) # type: ignore
        self.reportIconBtn.toggled['bool'].connect(self.reportBtn.setChecked) # type: ignore
        self.reportBtn.toggled['bool'].connect(self.reportIconBtn.setChecked) # type: ignore
        self.notificationsIconBtn.toggled['bool'].connect(self.notificationsBtn.setChecked) # type: ignore
        self.notificationsBtn.toggled['bool'].connect(self.notificationsIconBtn.setChecked) # type: ignore
        self.logoutIconBtn.toggled['bool'].connect(self.logoutBtn.setChecked) # type: ignore
        self.logoutBtn.toggled['bool'].connect(self.logoutIconBtn.setChecked) # type: ignore
        self.menuBtn.toggled['bool'].connect(self.iconOnlyWidget.setHidden) # type: ignore
        self.menuBtn.toggled['bool'].connect(self.iconNameWidget.setVisible) # type: ignore
        self.profileBtn.toggled['bool'].connect(self.profileBtnQuickAccess.setChecked) # type: ignore
        self.profileBtnQuickAccess.toggled['bool'].connect(self.profileIconBtn.setChecked) # type: ignore
        self.profileIconBtn.toggled['bool'].connect(self.profileBtnQuickAccess.setChecked) # type: ignore
        self.profileBtnQuickAccess.toggled['bool'].connect(self.profileBtn.setChecked) # type: ignore
        self.reportLogsIconBtn.toggled['bool'].connect(self.reportLogsBtn.setChecked) # type: ignore
        self.reportLogsBtn.toggled['bool'].connect(self.reportLogsIconBtn.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ApplicantDash)

    def retranslateUi(self, ApplicantDash):
        _translate = QtCore.QCoreApplication.translate
        ApplicantDash.setWindowTitle(_translate("ApplicantDash", "MainWindow"))
        self.welcomeLabel.setText(_translate("ApplicantDash", "Welcome"))
        self.usernameLabel.setText(_translate("ApplicantDash", "Applicant/Admin"))
        self.homeBtn.setText(_translate("ApplicantDash", "Home"))
        self.scholarshipBtn.setText(_translate("ApplicantDash", "Scholarships"))
        self.reportBtn.setText(_translate("ApplicantDash", "Report"))
        self.reportLogsBtn.setText(_translate("ApplicantDash", "Report Logs"))
        self.notificationsBtn.setText(_translate("ApplicantDash", "Notifications"))
        self.profileBtn.setText(_translate("ApplicantDash", "Profile settings"))
        self.logoutBtn.setText(_translate("ApplicantDash", "Logout"))
        self.homeScreenUsernameLabel.setText(_translate("ApplicantDash", "HELLO \"nAME\""))
        self.totalNumberOfApplicantsLabelHome.setText(_translate("ApplicantDash", "TOTAL NUMBER OF APPLICANTS: RAND_NUM"))
        self.totalNumOfScholarshipsLabelHome.setText(_translate("ApplicantDash", "TOTAL NUMBER OF SCHOLARSHIPS: RAND_NUM"))
        self.chart1Label.setText(_translate("ApplicantDash", "Chart1 Label..."))
        self.chart2Label.setText(_translate("ApplicantDash", "Chart2 Label..."))
        self.changeChartBtn.setText(_translate("ApplicantDash", "CHANGE"))
        self.label.setText(_translate("ApplicantDash", "SCHOLARSHIPS"))
        self.label_14.setText(_translate("ApplicantDash", "REPORTS"))
        self.label_21.setText(_translate("ApplicantDash", "Financial Amount"))
        self.label_13.setText(_translate("ApplicantDash", "Most Applied Scholarships"))
        self.label_4.setText(_translate("ApplicantDash", "Applicants per Country"))
        self.label_9.setText(_translate("ApplicantDash", "Common programs"))
        self.label_11.setText(_translate("ApplicantDash", "Appliant Education Level"))
        self.label_8.setText(_translate("ApplicantDash", "APPLICANT DATA"))
        self.label_18.setText(_translate("ApplicantDash", "Schemes Available"))
        self.totalNumOfScholarshipsLabelReports.setText(_translate("ApplicantDash", "Total Number of Scholarships:"))
        self.label_15.setText(_translate("ApplicantDash", "Scheme Ratio"))
        self.label_10.setText(_translate("ApplicantDash", "SCHOLARSHIP DATA"))
        self.printReportBtn.setText(_translate("ApplicantDash", "PRINT REPORT"))
        self.notificationPageTitleLabel.setText(_translate("ApplicantDash", "NOTIFICATIONS"))
        self.notiFilterCombo.setItemText(0, _translate("ApplicantDash", "All"))
        self.notiFilterCombo.setItemText(1, _translate("ApplicantDash", "unseen"))
        self.notiFilterCombo.setItemText(2, _translate("ApplicantDash", "seen"))
        self.noftiFilterbtn.setText(_translate("ApplicantDash", "FILTER"))
        self.label_2.setText(_translate("ApplicantDash", "PROFILE"))
        self.usenameLabelProfile.setText(_translate("ApplicantDash", "USERNAME HERE"))
        self.label_5.setText(_translate("ApplicantDash", "Username"))
        self.changeUsernameBtn.setText(_translate("ApplicantDash", "Change"))
        self.label_6.setText(_translate("ApplicantDash", "Email"))
        self.changeEmailBtn.setText(_translate("ApplicantDash", "Change"))
        self.label_7.setText(_translate("ApplicantDash", "Password"))
        self.changePassBtn.setText(_translate("ApplicantDash", "Change"))
        self.dateJoinedLabel.setText(_translate("ApplicantDash", "DATE JOINED: date"))
        self.LogoutBtn.setText(_translate("ApplicantDash", "LOGOUT"))
        self.label_3.setText(_translate("ApplicantDash", "REPORT LOGS"))
        self.label_12.setText(_translate("ApplicantDash", "NO INFORMATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicantDash = QtWidgets.QMainWindow()
    ui = Ui_ApplicantDash()
    ui.setupUi(ApplicantDash)
    ApplicantDash.show()
    sys.exit(app.exec())
