# Form implementation generated from reading ui file 'applicantDetails.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicantDetails(object):
    def setupUi(self, ApplicantDetails):
        ApplicantDetails.setObjectName("ApplicantDetails")
        ApplicantDetails.resize(489, 657)
        ApplicantDetails.setMinimumSize(QtCore.QSize(489, 657))
        ApplicantDetails.setMaximumSize(QtCore.QSize(489, 657))
        ApplicantDetails.setStyleSheet("QWidget{\n"
"    background-color: rgb(6, 57, 112);\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(1, 14, 27);\n"
"    padding: 7px;\n"
"    border-radius: 7px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ApplicantDetails)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(40, -1, 40, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(parent=ApplicantDetails)
        self.label.setStyleSheet("margin-bottom: 40px;\n"
"margin-top: 40px;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.emailLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.emailLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout.addWidget(self.emailLabel)
        self.ageLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.ageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ageLabel.setObjectName("ageLabel")
        self.verticalLayout.addWidget(self.ageLabel)
        self.genderLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.genderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.genderLabel.setObjectName("genderLabel")
        self.verticalLayout.addWidget(self.genderLabel)
        self.rankLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.rankLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rankLabel.setObjectName("rankLabel")
        self.verticalLayout.addWidget(self.rankLabel)
        self.nationalityLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.nationalityLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nationalityLabel.setObjectName("nationalityLabel")
        self.verticalLayout.addWidget(self.nationalityLabel)
        self.eduLevelLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.eduLevelLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.eduLevelLabel.setObjectName("eduLevelLabel")
        self.verticalLayout.addWidget(self.eduLevelLabel)
        self.dobLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.dobLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dobLabel.setObjectName("dobLabel")
        self.verticalLayout.addWidget(self.dobLabel)
        self.assessScoreLabel = QtWidgets.QLabel(parent=ApplicantDetails)
        self.assessScoreLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.assessScoreLabel.setObjectName("assessScoreLabel")
        self.verticalLayout.addWidget(self.assessScoreLabel)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.backBtn = QtWidgets.QPushButton(parent=ApplicantDetails)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.backBtn.setStyleSheet("")
        self.backBtn.setObjectName("backBtn")
        self.verticalLayout_2.addWidget(self.backBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(ApplicantDetails)
        QtCore.QMetaObject.connectSlotsByName(ApplicantDetails)

    def retranslateUi(self, ApplicantDetails):
        _translate = QtCore.QCoreApplication.translate
        ApplicantDetails.setWindowTitle(_translate("ApplicantDetails", "Form"))
        self.label.setText(_translate("ApplicantDetails", "Applicant Details"))
        self.nameLabel.setText(_translate("ApplicantDetails", "Name: "))
        self.emailLabel.setText(_translate("ApplicantDetails", "Email: "))
        self.ageLabel.setText(_translate("ApplicantDetails", "Age: "))
        self.genderLabel.setText(_translate("ApplicantDetails", "Gender:"))
        self.rankLabel.setText(_translate("ApplicantDetails", "Rank: "))
        self.nationalityLabel.setText(_translate("ApplicantDetails", "Nationality: "))
        self.eduLevelLabel.setText(_translate("ApplicantDetails", "Education Level: "))
        self.dobLabel.setText(_translate("ApplicantDetails", "DOB: "))
        self.assessScoreLabel.setText(_translate("ApplicantDetails", "Assessment Score: "))
        self.backBtn.setText(_translate("ApplicantDetails", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicantDetails = QtWidgets.QWidget()
    ui = Ui_ApplicantDetails()
    ui.setupUi(ApplicantDetails)
    ApplicantDetails.show()
    sys.exit(app.exec())
