# Form implementation generated from reading ui file 'dash.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import myRes


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 700)
        MainWindow.setStyleSheet("background-color: rgb(20, 41, 63);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.iconOnlyWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconOnlyWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(11, 100, 197);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(1, 14, 27);\n"
"    height:40px;\n"
"    border:none;\n"
"    padding:7px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:checked{\n"
"    border: 2px solid;\n"
"    border-color:black;\n"
"    border-radius:10px;\n"
"}")
        self.iconOnlyWidget.setObjectName("iconOnlyWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.iconOnlyWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.smallNavIcon = QtWidgets.QLabel(parent=self.iconOnlyWidget)
        self.smallNavIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.smallNavIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.smallNavIcon.setText("")
        self.smallNavIcon.setPixmap(QtGui.QPixmap(":/icons/SMsysIcon.png"))
        self.smallNavIcon.setScaledContents(True)
        self.smallNavIcon.setObjectName("smallNavIcon")
        self.horizontalLayout_3.addWidget(self.smallNavIcon)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.homeIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.homeIconBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeIconBtn.setIcon(icon)
        self.homeIconBtn.setCheckable(True)
        self.homeIconBtn.setAutoExclusive(True)
        self.homeIconBtn.setObjectName("homeIconBtn")
        self.verticalLayout_3.addWidget(self.homeIconBtn)
        self.scholarshipIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.scholarshipIconBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/manageScholarship.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.scholarshipIconBtn.setIcon(icon1)
        self.scholarshipIconBtn.setCheckable(True)
        self.scholarshipIconBtn.setAutoExclusive(True)
        self.scholarshipIconBtn.setObjectName("scholarshipIconBtn")
        self.verticalLayout_3.addWidget(self.scholarshipIconBtn)
        self.reportIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.reportIconBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/report.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.reportIconBtn.setIcon(icon2)
        self.reportIconBtn.setCheckable(True)
        self.reportIconBtn.setAutoExclusive(True)
        self.reportIconBtn.setObjectName("reportIconBtn")
        self.verticalLayout_3.addWidget(self.reportIconBtn)
        self.notificationsIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.notificationsIconBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/notification.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.notificationsIconBtn.setIcon(icon3)
        self.notificationsIconBtn.setCheckable(True)
        self.notificationsIconBtn.setAutoExclusive(True)
        self.notificationsIconBtn.setObjectName("notificationsIconBtn")
        self.verticalLayout_3.addWidget(self.notificationsIconBtn)
        self.profileIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.profileIconBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profileIconBtn.setIcon(icon4)
        self.profileIconBtn.setCheckable(True)
        self.profileIconBtn.setAutoExclusive(True)
        self.profileIconBtn.setObjectName("profileIconBtn")
        self.verticalLayout_3.addWidget(self.profileIconBtn)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 203, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.logoutIconBtn = QtWidgets.QPushButton(parent=self.iconOnlyWidget)
        self.logoutIconBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/powerBTN.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.logoutIconBtn.setIcon(icon5)
        self.logoutIconBtn.setCheckable(True)
        self.logoutIconBtn.setAutoExclusive(True)
        self.logoutIconBtn.setObjectName("logoutIconBtn")
        self.verticalLayout_5.addWidget(self.logoutIconBtn)
        self.gridLayout.addWidget(self.iconOnlyWidget, 0, 0, 1, 1)
        self.iconNameWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconNameWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(11, 100, 197);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(1, 14, 27);\n"
"    font: 12pt \"Yu Gothic UI\";\n"
"    text-align: left;\n"
"    height:40px;\n"
"    border:none;\n"
"    padding:7px;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(1, 14, 27);\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"    \n"
"    background-color: rgb(20, 41, 63);\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    padding-right:10px;\n"
"}")
        self.iconNameWidget.setObjectName("iconNameWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.iconNameWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 20, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fullNavIcon = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.fullNavIcon.setMinimumSize(QtCore.QSize(40, 40))
        self.fullNavIcon.setMaximumSize(QtCore.QSize(40, 40))
        self.fullNavIcon.setText("")
        self.fullNavIcon.setPixmap(QtGui.QPixmap(":/icons/SMsysIcon.png"))
        self.fullNavIcon.setScaledContents(True)
        self.fullNavIcon.setObjectName("fullNavIcon")
        self.horizontalLayout_2.addWidget(self.fullNavIcon)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomLabel = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.welcomLabel.setObjectName("welcomLabel")
        self.verticalLayout.addWidget(self.welcomLabel)
        self.usernameLabel = QtWidgets.QLabel(parent=self.iconNameWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.homeBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.homeBtn.setIcon(icon)
        self.homeBtn.setCheckable(True)
        self.homeBtn.setAutoExclusive(True)
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout_2.addWidget(self.homeBtn)
        self.scholarshipBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.scholarshipBtn.setIcon(icon1)
        self.scholarshipBtn.setCheckable(True)
        self.scholarshipBtn.setAutoExclusive(True)
        self.scholarshipBtn.setObjectName("scholarshipBtn")
        self.verticalLayout_2.addWidget(self.scholarshipBtn)
        self.reportBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.reportBtn.setIcon(icon2)
        self.reportBtn.setCheckable(True)
        self.reportBtn.setAutoExclusive(True)
        self.reportBtn.setObjectName("reportBtn")
        self.verticalLayout_2.addWidget(self.reportBtn)
        self.notificationsBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.notificationsBtn.setIcon(icon3)
        self.notificationsBtn.setCheckable(True)
        self.notificationsBtn.setAutoExclusive(True)
        self.notificationsBtn.setObjectName("notificationsBtn")
        self.verticalLayout_2.addWidget(self.notificationsBtn)
        self.profileBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.profileBtn.setIcon(icon4)
        self.profileBtn.setCheckable(True)
        self.profileBtn.setAutoExclusive(True)
        self.profileBtn.setObjectName("profileBtn")
        self.verticalLayout_2.addWidget(self.profileBtn)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 209, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.logoutBtn = QtWidgets.QPushButton(parent=self.iconNameWidget)
        self.logoutBtn.setIcon(icon5)
        self.logoutBtn.setCheckable(True)
        self.logoutBtn.setAutoExclusive(True)
        self.logoutBtn.setObjectName("logoutBtn")
        self.verticalLayout_4.addWidget(self.logoutBtn)
        self.gridLayout.addWidget(self.iconNameWidget, 0, 1, 1, 1)
        self.mainWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.headerWidget = QtWidgets.QWidget(parent=self.mainWidget)
        self.headerWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(6, 57, 112);\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border: 2px solid;\n"
"    border-color: black;\n"
"    border-radius: 10px;\n"
"    \n"
"}")
        self.headerWidget.setObjectName("headerWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menuBtn = QtWidgets.QPushButton(parent=self.headerWidget)
        self.menuBtn.setMinimumSize(QtCore.QSize(40, 40))
        self.menuBtn.setMaximumSize(QtCore.QSize(40, 40))
        self.menuBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menuBtn.setIcon(icon6)
        self.menuBtn.setCheckable(True)
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_4.addWidget(self.menuBtn)
        spacerItem2 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchBarTxt = QtWidgets.QLineEdit(parent=self.headerWidget)
        self.searchBarTxt.setObjectName("searchBarTxt")
        self.horizontalLayout.addWidget(self.searchBarTxt)
        self.searchBtn = QtWidgets.QPushButton(parent=self.headerWidget)
        self.searchBtn.setStyleSheet("QPushButton:checked{\n"
"    border: none;\n"
"    \n"
"}")
        self.searchBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchBtn.setIcon(icon7)
        self.searchBtn.setCheckable(True)
        self.searchBtn.setObjectName("searchBtn")
        self.horizontalLayout.addWidget(self.searchBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(149, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.profileBtnQuickAccess = QtWidgets.QPushButton(parent=self.headerWidget)
        self.profileBtnQuickAccess.setMinimumSize(QtCore.QSize(40, 40))
        self.profileBtnQuickAccess.setMaximumSize(QtCore.QSize(40, 40))
        self.profileBtnQuickAccess.setStyleSheet("")
        self.profileBtnQuickAccess.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.profileBtnQuickAccess.setIcon(icon8)
        self.profileBtnQuickAccess.setCheckable(True)
        self.profileBtnQuickAccess.setAutoExclusive(True)
        self.profileBtnQuickAccess.setObjectName("profileBtnQuickAccess")
        self.horizontalLayout_4.addWidget(self.profileBtnQuickAccess)
        self.verticalLayout_6.addWidget(self.headerWidget)
        self.mainDisplayWidget = QtWidgets.QStackedWidget(parent=self.mainWidget)
        self.mainDisplayWidget.setStyleSheet("QWidget{\n"
"    background-color: rgb(6, 57, 112);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 700 16pt \"Segoe UI\";\n"
"}\n"
"\n"
"QTableWidget{\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(1, 14, 27);\n"
"    padding: 17px;\n"
"    border-radius: 10px;\n"
"    margin-bottom:20px;\n"
"    margin-right:20px;\n"
"    margin-left:20px;\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"\n"
"}\n"
"")
        self.mainDisplayWidget.setObjectName("mainDisplayWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.homScreenUsernameLabel = QtWidgets.QLabel(parent=self.home)
        self.homScreenUsernameLabel.setObjectName("homScreenUsernameLabel")
        self.horizontalLayout_5.addWidget(self.homScreenUsernameLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 20, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.recentApplicantionsLabel = QtWidgets.QLabel(parent=self.home)
        self.recentApplicantionsLabel.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.recentApplicantionsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recentApplicantionsLabel.setObjectName("recentApplicantionsLabel")
        self.horizontalLayout_6.addWidget(self.recentApplicantionsLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.recentApplicantionsLabel_2 = QtWidgets.QLabel(parent=self.home)
        self.recentApplicantionsLabel_2.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.recentApplicantionsLabel_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recentApplicantionsLabel_2.setObjectName("recentApplicantionsLabel_2")
        self.horizontalLayout_6.addWidget(self.recentApplicantionsLabel_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(20, -1, 20, 20)
        self.horizontalLayout_7.setSpacing(30)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.recentApplicationsTableWidget = QtWidgets.QTableWidget(parent=self.home)
        self.recentApplicationsTableWidget.setObjectName("recentApplicationsTableWidget")
        self.recentApplicationsTableWidget.setColumnCount(0)
        self.recentApplicationsTableWidget.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.recentApplicationsTableWidget)
        self.applicantRankTableWidget = QtWidgets.QTableWidget(parent=self.home)
        self.applicantRankTableWidget.setObjectName("applicantRankTableWidget")
        self.applicantRankTableWidget.setColumnCount(0)
        self.applicantRankTableWidget.setRowCount(0)
        self.horizontalLayout_7.addWidget(self.applicantRankTableWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.recentApplicantionsLabel_3 = QtWidgets.QLabel(parent=self.home)
        self.recentApplicantionsLabel_3.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.recentApplicantionsLabel_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.recentApplicantionsLabel_3.setObjectName("recentApplicantionsLabel_3")
        self.verticalLayout_9.addWidget(self.recentApplicantionsLabel_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(20, 0, 20, 20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listofScholarshipsTableWidget = QtWidgets.QTableWidget(parent=self.home)
        self.listofScholarshipsTableWidget.setObjectName("listofScholarshipsTableWidget")
        self.listofScholarshipsTableWidget.setColumnCount(0)
        self.listofScholarshipsTableWidget.setRowCount(0)
        self.verticalLayout_8.addWidget(self.listofScholarshipsTableWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 20, -1, 20)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.totalAppliacantslabel = QtWidgets.QLabel(parent=self.home)
        self.totalAppliacantslabel.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.totalAppliacantslabel.setObjectName("totalAppliacantslabel")
        self.verticalLayout_7.addWidget(self.totalAppliacantslabel)
        self.totalScholarshipsLabel = QtWidgets.QLabel(parent=self.home)
        self.totalScholarshipsLabel.setStyleSheet("\n"
"font: 12pt \"Segoe UI\";")
        self.totalScholarshipsLabel.setObjectName("totalScholarshipsLabel")
        self.verticalLayout_7.addWidget(self.totalScholarshipsLabel)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 3, 0, 1, 1)
        self.mainDisplayWidget.addWidget(self.home)
        self.manageScholarships = QtWidgets.QWidget()
        self.manageScholarships.setObjectName("manageScholarships")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.manageScholarships)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(20, -1, 20, 40)
        self.verticalLayout_10.setSpacing(20)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(parent=self.manageScholarships)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.manageScholarships)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_10.addWidget(self.tableWidget)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.manageScholarships)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 1, 0, 1, 1)
        self.mainDisplayWidget.addWidget(self.manageScholarships)
        self.profile = QtWidgets.QWidget()
        self.profile.setObjectName("profile")
        self.profileLabel = QtWidgets.QLabel(parent=self.profile)
        self.profileLabel.setGeometry(QtCore.QRect(140, 140, 251, 101))
        self.profileLabel.setObjectName("profileLabel")
        self.mainDisplayWidget.addWidget(self.profile)
        self.notificationsPage = QtWidgets.QWidget()
        self.notificationsPage.setObjectName("notificationsPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.notificationsPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(20, -1, 20, 20)
        self.verticalLayout_11.setSpacing(20)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.notificationPageTitleLabel = QtWidgets.QLabel(parent=self.notificationsPage)
        self.notificationPageTitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.notificationPageTitleLabel.setObjectName("notificationPageTitleLabel")
        self.verticalLayout_11.addWidget(self.notificationPageTitleLabel)
        self.notificationsTableWidget = QtWidgets.QTableWidget(parent=self.notificationsPage)
        self.notificationsTableWidget.setObjectName("notificationsTableWidget")
        self.notificationsTableWidget.setColumnCount(0)
        self.notificationsTableWidget.setRowCount(0)
        self.verticalLayout_11.addWidget(self.notificationsTableWidget)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(20, -1, 20, 80)
        self.verticalLayout_12.setSpacing(30)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.notificationsPage)
        self.label_3.setStyleSheet("font: 600 12pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.notificationTitleLabe = QtWidgets.QLabel(parent=self.notificationsPage)
        self.notificationTitleLabe.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.notificationTitleLabe.setObjectName("notificationTitleLabe")
        self.horizontalLayout_8.addWidget(self.notificationTitleLabe)
        self.notificationTitleTxt = QtWidgets.QLineEdit(parent=self.notificationsPage)
        self.notificationTitleTxt.setObjectName("notificationTitleTxt")
        self.horizontalLayout_8.addWidget(self.notificationTitleTxt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.notificationEmailLabel = QtWidgets.QLabel(parent=self.notificationsPage)
        self.notificationEmailLabel.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.notificationEmailLabel.setObjectName("notificationEmailLabel")
        self.horizontalLayout_9.addWidget(self.notificationEmailLabel)
        self.notificationEmailTxt = QtWidgets.QLineEdit(parent=self.notificationsPage)
        self.notificationEmailTxt.setObjectName("notificationEmailTxt")
        self.horizontalLayout_9.addWidget(self.notificationEmailTxt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.notificationMsgLabel = QtWidgets.QLabel(parent=self.notificationsPage)
        self.notificationMsgLabel.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.notificationMsgLabel.setObjectName("notificationMsgLabel")
        self.horizontalLayout_10.addWidget(self.notificationMsgLabel)
        self.notificationMsgTxt = QtWidgets.QLineEdit(parent=self.notificationsPage)
        self.notificationMsgTxt.setStyleSheet("")
        self.notificationMsgTxt.setObjectName("notificationMsgTxt")
        self.horizontalLayout_10.addWidget(self.notificationMsgTxt)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.notificationSendBtn = QtWidgets.QPushButton(parent=self.notificationsPage)
        self.notificationSendBtn.setObjectName("notificationSendBtn")
        self.gridLayout_4.addWidget(self.notificationSendBtn, 2, 0, 1, 1)
        self.mainDisplayWidget.addWidget(self.notificationsPage)
        self.report = QtWidgets.QWidget()
        self.report.setObjectName("report")
        self.reportsLabel = QtWidgets.QLabel(parent=self.report)
        self.reportsLabel.setGeometry(QtCore.QRect(150, 130, 251, 101))
        self.reportsLabel.setObjectName("reportsLabel")
        self.mainDisplayWidget.addWidget(self.report)
        self.verticalLayout_6.addWidget(self.mainDisplayWidget)
        self.gridLayout.addWidget(self.mainWidget, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainDisplayWidget.setCurrentIndex(3)
        self.menuBtn.toggled['bool'].connect(self.iconOnlyWidget.setHidden) # type: ignore
        self.menuBtn.toggled['bool'].connect(self.iconNameWidget.setVisible) # type: ignore
        self.profileIconBtn.toggled['bool'].connect(self.profileBtn.setChecked) # type: ignore
        self.reportIconBtn.toggled['bool'].connect(self.reportBtn.setChecked) # type: ignore
        self.scholarshipIconBtn.toggled['bool'].connect(self.scholarshipBtn.setChecked) # type: ignore
        self.homeIconBtn.toggled['bool'].connect(self.homeBtn.setChecked) # type: ignore
        self.logoutIconBtn.toggled['bool'].connect(self.logoutBtn.setChecked) # type: ignore
        self.homeBtn.toggled['bool'].connect(self.homeIconBtn.setChecked) # type: ignore
        self.scholarshipBtn.toggled['bool'].connect(self.scholarshipIconBtn.setChecked) # type: ignore
        self.reportBtn.toggled['bool'].connect(self.reportIconBtn.setChecked) # type: ignore
        self.profileBtn.toggled['bool'].connect(self.profileIconBtn.setChecked) # type: ignore
        self.logoutBtn.toggled['bool'].connect(self.logoutIconBtn.setChecked) # type: ignore
        self.notificationsIconBtn.toggled['bool'].connect(self.notificationsBtn.setChecked) # type: ignore
        self.notificationsBtn.toggled['bool'].connect(self.notificationsIconBtn.setChecked) # type: ignore
        self.profileBtn.toggled['bool'].connect(self.profileBtnQuickAccess.setChecked) # type: ignore
        self.profileBtnQuickAccess.toggled['bool'].connect(self.profileBtn.setChecked) # type: ignore
        self.profileBtnQuickAccess.toggled['bool'].connect(self.profileIconBtn.setChecked) # type: ignore
        self.profileIconBtn.toggled['bool'].connect(self.profileBtnQuickAccess.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomLabel.setText(_translate("MainWindow", "Welcome"))
        self.usernameLabel.setText(_translate("MainWindow", "Applicant/Admin"))
        self.homeBtn.setText(_translate("MainWindow", "Home"))
        self.scholarshipBtn.setText(_translate("MainWindow", "Manage Scholarships"))
        self.reportBtn.setText(_translate("MainWindow", "Report"))
        self.notificationsBtn.setText(_translate("MainWindow", "Notifications"))
        self.profileBtn.setText(_translate("MainWindow", "Profile settings"))
        self.logoutBtn.setText(_translate("MainWindow", "Logout"))
        self.homScreenUsernameLabel.setText(_translate("MainWindow", "HELLO \"nAME\""))
        self.recentApplicantionsLabel.setText(_translate("MainWindow", "RECENT APPLICANTIONS              "))
        self.recentApplicantionsLabel_2.setText(_translate("MainWindow", "APPLICANT RANK"))
        self.recentApplicantionsLabel_3.setText(_translate("MainWindow", "SCHOLARSHIP LIST"))
        self.totalAppliacantslabel.setText(_translate("MainWindow", "TOTAL NUMBER OF APPLICANTS: RAND_NUM"))
        self.totalScholarshipsLabel.setText(_translate("MainWindow", "TOTAL NUMBER OF SCHOLARSHIPS: RAND_NUM"))
        self.label.setText(_translate("MainWindow", "SCHOLARSHIPS"))
        self.pushButton.setText(_translate("MainWindow", "UPLOAD SCHOLARSHIP"))
        self.profileLabel.setText(_translate("MainWindow", "profile"))
        self.notificationPageTitleLabel.setText(_translate("MainWindow", "NOTIFICATIONS"))
        self.label_3.setText(_translate("MainWindow", "Send Notifications"))
        self.notificationTitleLabe.setText(_translate("MainWindow", "Title:                  "))
        self.notificationEmailLabel.setText(_translate("MainWindow", "Recipient Email: "))
        self.notificationMsgLabel.setText(_translate("MainWindow", "Message:           "))
        self.notificationSendBtn.setText(_translate("MainWindow", "SEND"))
        self.reportsLabel.setText(_translate("MainWindow", "Reports"))
