# Form implementation generated from reading ui file 'notificationDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NotificationDisplay(object):
    def setupUi(self, NotificationDisplay):
        NotificationDisplay.setObjectName("NotificationDisplay")
        NotificationDisplay.resize(413, 470)
        NotificationDisplay.setMinimumSize(QtCore.QSize(413, 470))
        NotificationDisplay.setMaximumSize(QtCore.QSize(413, 470))
        NotificationDisplay.setStyleSheet("QWidget{\n"
"    background-color:rgb(6, 57, 112);\n"
"}\n"
"QLabel{\n"
"    \n"
"    font: 600 11pt \"Segoe UI\";\n"
"}\n"
"QPushButton{\n"
"    margin-top:10px;\n"
"    margin-bottom:20px;\n"
"    margin-left:5px;\n"
"    margin-right:5px;\n"
"    padding:7px;\n"
"    \n"
"    background-color: rgb(20, 41, 63);\n"
"    font: 600 11pt \"Segoe UI\";\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NotificationDisplay)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=NotificationDisplay)
        self.label_3.setStyleSheet("margin-top:30px;\n"
"margin-bottom:30px;\n"
"font: 600 14pt \"Segoe UI\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.line_2 = QtWidgets.QFrame(parent=NotificationDisplay)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.senderLabel = QtWidgets.QLabel(parent=NotificationDisplay)
        self.senderLabel.setStyleSheet("")
        self.senderLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.senderLabel.setObjectName("senderLabel")
        self.verticalLayout_2.addWidget(self.senderLabel)
        self.recipientLabel = QtWidgets.QLabel(parent=NotificationDisplay)
        self.recipientLabel.setStyleSheet("")
        self.recipientLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.recipientLabel.setObjectName("recipientLabel")
        self.verticalLayout_2.addWidget(self.recipientLabel)
        self.statusLabel = QtWidgets.QLabel(parent=NotificationDisplay)
        self.statusLabel.setStyleSheet("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)
        self.titleLabel = QtWidgets.QLabel(parent=NotificationDisplay)
        self.titleLabel.setStyleSheet("margin-bottom:10px;")
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.scrollArea = QtWidgets.QScrollArea(parent=NotificationDisplay)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 393, 154))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(40)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.msgLabel.setWordWrap(True)
        self.msgLabel.setObjectName("msgLabel")
        self.verticalLayout.addWidget(self.msgLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.line = QtWidgets.QFrame(parent=NotificationDisplay)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.cancelBtn = QtWidgets.QPushButton(parent=NotificationDisplay)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout_2.addWidget(self.cancelBtn)

        self.retranslateUi(NotificationDisplay)
        QtCore.QMetaObject.connectSlotsByName(NotificationDisplay)

    def retranslateUi(self, NotificationDisplay):
        _translate = QtCore.QCoreApplication.translate
        NotificationDisplay.setWindowTitle(_translate("NotificationDisplay", "Form"))
        self.label_3.setText(_translate("NotificationDisplay", "NOTIFICATIONS"))
        self.senderLabel.setText(_translate("NotificationDisplay", "From:"))
        self.recipientLabel.setText(_translate("NotificationDisplay", "To: "))
        self.statusLabel.setText(_translate("NotificationDisplay", "Status: "))
        self.titleLabel.setText(_translate("NotificationDisplay", "Message Title:"))
        self.msgLabel.setText(_translate("NotificationDisplay", "Message"))
        self.cancelBtn.setText(_translate("NotificationDisplay", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NotificationDisplay = QtWidgets.QWidget()
    ui = Ui_NotificationDisplay()
    ui.setupUi(NotificationDisplay)
    NotificationDisplay.show()
    sys.exit(app.exec())
