# Form implementation generated from reading ui file 'applicantCard.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ApplicantCardForm(object):
    def setupUi(self, ApplicantCardForm):
        ApplicantCardForm.setObjectName("ApplicantCardForm")
        ApplicantCardForm.resize(734, 108)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(ApplicantCardForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(parent=ApplicantCardForm)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.nameLabel = QtWidgets.QLabel(parent=ApplicantCardForm)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.emailLabel = QtWidgets.QLabel(parent=ApplicantCardForm)
        self.emailLabel.setObjectName("emailLabel")
        self.verticalLayout.addWidget(self.emailLabel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.delBtn = QtWidgets.QPushButton(parent=ApplicantCardForm)
        self.delBtn.setObjectName("delBtn")
        self.horizontalLayout.addWidget(self.delBtn)
        self.viewBtn = QtWidgets.QPushButton(parent=ApplicantCardForm)
        self.viewBtn.setObjectName("viewBtn")
        self.horizontalLayout.addWidget(self.viewBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(parent=ApplicantCardForm)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(547, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)

        self.retranslateUi(ApplicantCardForm)
        QtCore.QMetaObject.connectSlotsByName(ApplicantCardForm)

    def retranslateUi(self, ApplicantCardForm):
        _translate = QtCore.QCoreApplication.translate
        ApplicantCardForm.setWindowTitle(_translate("ApplicantCardForm", "Form"))
        self.nameLabel.setText(_translate("ApplicantCardForm", "Name: DemoName"))
        self.emailLabel.setText(_translate("ApplicantCardForm", "Email: DemoEmail:"))
        self.delBtn.setText(_translate("ApplicantCardForm", "Delete"))
        self.viewBtn.setText(_translate("ApplicantCardForm", "View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicantCardForm = QtWidgets.QWidget()
    ui = Ui_ApplicantCardForm()
    ui.setupUi(ApplicantCardForm)
    ApplicantCardForm.show()
    sys.exit(app.exec())
