# Form implementation generated from reading ui file 'critical.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_criticalReasoningForm(object):
    def setupUi(self, criticalReasoningForm):
        criticalReasoningForm.setObjectName("criticalReasoningForm")
        criticalReasoningForm.resize(841, 586)
        criticalReasoningForm.setStyleSheet("QWidget{\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(criticalReasoningForm)
        self.gridLayout.setObjectName("gridLayout")
        self.criticalReasoningStackedWidget = QtWidgets.QStackedWidget(parent=criticalReasoningForm)
        self.criticalReasoningStackedWidget.setObjectName("criticalReasoningStackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setStyleSheet("font: 700 16pt \"Segoe UI\";\n"
"margin-top:30px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(50, 40, 50, 40)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.page)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=self.page)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.page)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.page)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_15 = QtWidgets.QLabel(parent=self.page)
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.startBtn = QtWidgets.QPushButton(parent=self.page)
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.startBtn.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"background-color: rgb(11, 100, 197);\n"
"padding:7px;\n"
"width:100px;")
        self.startBtn.setDefault(False)
        self.startBtn.setFlat(False)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.criticalReasoningStackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.questionHeader = QtWidgets.QLabel(parent=self.page_2)
        self.questionHeader.setStyleSheet("font: 700 16pt \"Segoe UI\";")
        self.questionHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.questionHeader.setObjectName("questionHeader")
        self.verticalLayout_6.addWidget(self.questionHeader)
        self.qTimer = QtWidgets.QLabel(parent=self.page_2)
        self.qTimer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.qTimer.setObjectName("qTimer")
        self.verticalLayout_6.addWidget(self.qTimer)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(70, 100, 40, 50)
        self.verticalLayout_7.setSpacing(40)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.question_txt = QtWidgets.QLabel(parent=self.page_2)
        self.question_txt.setWordWrap(True)
        self.question_txt.setObjectName("question_txt")
        self.verticalLayout_7.addWidget(self.question_txt)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(40, 60, 60, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.yesBtn = QtWidgets.QPushButton(parent=self.page_2)
        self.yesBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.yesBtn.setStyleSheet("QPushButton{\n"
"font: 600 12pt \"Segoe UI\";\n"
"\n"
"padding:15px;\n"
"width:100px;\n"
"border: 1px solid white;\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border:none;\n"
"    background-color: rgb(11, 100, 197);\n"
"color:black;\n"
"}\n"
"QPushButton::checked{\n"
"border:none;\n"
"background-color: rgb(11, 100, 197);\n"
"color:black;\n"
"}")
        self.yesBtn.setCheckable(True)
        self.yesBtn.setAutoExclusive(True)
        self.yesBtn.setFlat(True)
        self.yesBtn.setObjectName("yesBtn")
        self.horizontalLayout_2.addWidget(self.yesBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.noBtn = QtWidgets.QPushButton(parent=self.page_2)
        self.noBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.noBtn.setStyleSheet("QPushButton{\n"
"font: 600 12pt \"Segoe UI\";\n"
"\n"
"padding:15px;\n"
"width:100px;\n"
"border: 1px solid white;\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"border:none;\n"
"background-color: rgb(11, 100, 197);\n"
"color:black;\n"
"}\n"
"\n"
"QPushButton::checked{\n"
"border:none;\n"
"background-color: rgb(11, 100, 197);\n"
"color:black;\n"
"}")
        self.noBtn.setCheckable(True)
        self.noBtn.setAutoExclusive(True)
        self.noBtn.setFlat(True)
        self.noBtn.setObjectName("noBtn")
        self.horizontalLayout_2.addWidget(self.noBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.qNextBtn = QtWidgets.QPushButton(parent=self.page_2)
        self.qNextBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.qNextBtn.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"background-color: rgb(11, 100, 197);\n"
"padding:7px;\n"
"width:100px;")
        self.qNextBtn.setDefault(False)
        self.qNextBtn.setFlat(False)
        self.qNextBtn.setObjectName("qNextBtn")
        self.horizontalLayout_3.addWidget(self.qNextBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.criticalReasoningStackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.criticalReasoningStackedWidget, 0, 0, 1, 1)

        self.retranslateUi(criticalReasoningForm)
        self.criticalReasoningStackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(criticalReasoningForm)

    def retranslateUi(self, criticalReasoningForm):
        _translate = QtCore.QCoreApplication.translate
        criticalReasoningForm.setWindowTitle(_translate("criticalReasoningForm", "Form"))
        self.label.setText(_translate("criticalReasoningForm", "CRITICAL  THINKING - ASSUMPTIONS"))
        self.label_2.setText(_translate("criticalReasoningForm", "Type: Identifying assumptions in arguments"))
        self.label_3.setText(_translate("criticalReasoningForm", "Instruction: Each question presents a short argument followed by a proposed assumption. Decide if the assumption is presupposed."))
        self.label_4.setText(_translate("criticalReasoningForm", "Example:"))
        self.label_5.setText(_translate("criticalReasoningForm", "Statement: Students should be given homework every day, because practice is necessary for learning."))
        self.label_6.setText(_translate("criticalReasoningForm", "Proposed Assumption: Homework provides practice."))
        self.label_7.setText(_translate("criticalReasoningForm", "Answer: Yes"))
        self.label_15.setText(_translate("criticalReasoningForm", "Explanation: The argument assumes that homework provides practice, otherwise the reasoning does not follow."))
        self.startBtn.setText(_translate("criticalReasoningForm", "START"))
        self.questionHeader.setText(_translate("criticalReasoningForm", "QUESTION..."))
        self.qTimer.setText(_translate("criticalReasoningForm", "00:00"))
        self.question_txt.setText(_translate("criticalReasoningForm", "QUESTION TXT..."))
        self.yesBtn.setText(_translate("criticalReasoningForm", "Yes"))
        self.noBtn.setText(_translate("criticalReasoningForm", "No"))
        self.qNextBtn.setText(_translate("criticalReasoningForm", "NEXT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    criticalReasoningForm = QtWidgets.QWidget()
    ui = Ui_criticalReasoningForm()
    ui.setupUi(criticalReasoningForm)
    criticalReasoningForm.show()
    sys.exit(app.exec())
