# Form implementation generated from reading ui file 'introPage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_introduction(object):
    def setupUi(self, introduction):
        introduction.setObjectName("introduction")
        introduction.resize(836, 576)
        introduction.setMinimumSize(QtCore.QSize(836, 576))
        introduction.setMaximumSize(QtCore.QSize(836, 576))
        introduction.setStyleSheet("QWidget{\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(introduction)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.beginBtn = QtWidgets.QPushButton(parent=introduction)
        self.beginBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.beginBtn.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"background-color: rgb(11, 100, 197);\n"
"padding:7px;\n"
"width:100px;")
        self.beginBtn.setDefault(False)
        self.beginBtn.setFlat(False)
        self.beginBtn.setObjectName("beginBtn")
        self.horizontalLayout.addWidget(self.beginBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 30, -1, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=introduction)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=introduction)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=introduction)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=introduction)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label_6 = QtWidgets.QLabel(parent=introduction)
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=introduction)
        self.label.setStyleSheet("font: 700 16pt \"Segoe UI\";\n"
"margin-top:40px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)

        self.retranslateUi(introduction)
        QtCore.QMetaObject.connectSlotsByName(introduction)

    def retranslateUi(self, introduction):
        _translate = QtCore.QCoreApplication.translate
        introduction.setWindowTitle(_translate("introduction", "Form"))
        self.beginBtn.setText(_translate("introduction", "BEGIN"))
        self.label_2.setText(_translate("introduction", "About"))
        self.label_3.setText(_translate("introduction", "You are about to write a series of amplitude tests. The total time for this Session is 6 minutes, each sub-test will consist of 5 questions. This test is only taken once .YOU MUST TAKE THE FIRST 4 TESTS"))
        self.label_4.setText(_translate("introduction", "Instructions"))
        self.label_5.setText(_translate("introduction", "The time limit is 1:30 minutes for each test, do not take too long to answer a question or it may run out. If you press next without answering the question no marks will be awarded for that question. You cannot skip a question. If you decide to close the app before finishing YOUR RESULTS WILL NOT BE SAVED."))
        self.label_6.setText(_translate("introduction", "When you are ready, click \"Begin\" to see instructions for the first sub-test."))
        self.label.setText(_translate("introduction", "INTRODUCTION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    introduction = QtWidgets.QWidget()
    ui = Ui_introduction()
    ui.setupUi(introduction)
    introduction.show()
    sys.exit(app.exec())
