# Form implementation generated from reading ui file 'uploadScholarships.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 344)
        Dialog.setMinimumSize(QtCore.QSize(390, 340))
        Dialog.setMaximumSize(QtCore.QSize(417, 349))
        Dialog.setStyleSheet("QDialog{\n"
"    \n"
"    background-color: rgb(11, 100, 197);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-right:40px;\n"
"    padding-left:40px;\n"
"    border: 1px solid;\n"
"    border-radius:10px;\n"
"    margin-bottom: 30px;\n"
"    background-color: rgb(1, 14, 27);\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    \n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    background-color: rgb(11, 100, 197);\n"
"    border-bottom: 1px solid white;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setStyleSheet("font: 600 14pt \"Segoe UI\";\n"
"margin-bottom:30px;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.scholarshipNameTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.scholarshipNameTxt.setObjectName("scholarshipNameTxt")
        self.horizontalLayout_5.addWidget(self.scholarshipNameTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.scholarshipDescriptionTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.scholarshipDescriptionTxt.setObjectName("scholarshipDescriptionTxt")
        self.horizontalLayout_4.addWidget(self.scholarshipDescriptionTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.scholarshipDeadlineTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.scholarshipDeadlineTxt.setObjectName("scholarshipDeadlineTxt")
        self.horizontalLayout_3.addWidget(self.scholarshipDeadlineTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.scholarshipFilepathTxt = QtWidgets.QLineEdit(parent=Dialog)
        self.scholarshipFilepathTxt.setObjectName("scholarshipFilepathTxt")
        self.horizontalLayout_2.addWidget(self.scholarshipFilepathTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uploadBtn = QtWidgets.QPushButton(parent=Dialog)
        self.uploadBtn.setObjectName("uploadBtn")
        self.horizontalLayout.addWidget(self.uploadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "Please Select a File"))
        self.label.setText(_translate("Dialog", "Scholarship Name:"))
        self.label_2.setText(_translate("Dialog", "Description:           "))
        self.label_3.setText(_translate("Dialog", "Deadline:               "))
        self.label_4.setText(_translate("Dialog", "File Path:               "))
        self.uploadBtn.setText(_translate("Dialog", "UPLOAD"))
        self.cancelBtn.setText(_translate("Dialog", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
