# Form implementation generated from reading ui file 'uploadscholarships.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(520, 518)
        Dialog.setMinimumSize(QtCore.QSize(520, 518))
        Dialog.setMaximumSize(QtCore.QSize(520, 518))
        Dialog.setStyleSheet("QDialog{\n"
"    \n"
"    \n"
"    background-color: rgb(11, 100, 197);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-right:40px;\n"
"    padding-left:40px;\n"
"    border: 1px solid;\n"
"    border-radius:10px;\n"
"    margin-bottom: 30px;\n"
"    background-color: rgb(1, 14, 27);\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    background-color: rgb(11, 100, 197);\n"
"    border-bottom: 1px solid white;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setContentsMargins(-1, 19, -1, 0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem)
        self.uploadBtn = QtWidgets.QPushButton(parent=Dialog)
        self.uploadBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.uploadBtn.setStyleSheet("background-color: rgb(1, 14, 27);")
        self.uploadBtn.setObjectName("uploadBtn")
        self.horizontalLayout_34.addWidget(self.uploadBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setStyleSheet("background-color: rgb(1, 14, 27);")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_34.addWidget(self.cancelBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_34, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setStyleSheet("background-color: rgb(11, 100, 197);")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 488, 1051))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents_4)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setContentsMargins(20, -1, 20, 20)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_41 = QtWidgets.QLabel(parent=self.widget)
        self.label_41.setStyleSheet("margin-bottom:17px;")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_19.addWidget(self.label_41)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 40)
        self.verticalLayout_20.setSpacing(15)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_42 = QtWidgets.QLabel(parent=self.widget)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_35.addWidget(self.label_42)
        self.scholarshipNameTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.scholarshipNameTxt.setObjectName("scholarshipNameTxt")
        self.horizontalLayout_35.addWidget(self.scholarshipNameTxt)
        self.verticalLayout_20.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_43 = QtWidgets.QLabel(parent=self.widget)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_36.addWidget(self.label_43)
        self.providerTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.providerTxt.setObjectName("providerTxt")
        self.horizontalLayout_36.addWidget(self.providerTxt)
        self.verticalLayout_20.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_44 = QtWidgets.QLabel(parent=self.widget)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_37.addWidget(self.label_44)
        self.typeCombo = QtWidgets.QComboBox(parent=self.widget)
        self.typeCombo.setStyleSheet("QComboBox{\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"    background-color: rgb(11, 100, 197);\n"
"    background:transparent;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"")
        self.typeCombo.setObjectName("typeCombo")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentNew")
        self.typeCombo.addItem(icon, "")
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentPageSetup")
        self.typeCombo.addItem(icon, "")
        self.horizontalLayout_37.addWidget(self.typeCombo)
        self.verticalLayout_20.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_45 = QtWidgets.QLabel(parent=self.widget)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_38.addWidget(self.label_45)
        self.subjectTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.subjectTxt.setObjectName("subjectTxt")
        self.horizontalLayout_38.addWidget(self.subjectTxt)
        self.verticalLayout_20.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_46 = QtWidgets.QLabel(parent=self.widget)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_39.addWidget(self.label_46)
        self.descripTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.descripTxt.setObjectName("descripTxt")
        self.horizontalLayout_39.addWidget(self.descripTxt)
        self.verticalLayout_20.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_47 = QtWidgets.QLabel(parent=self.widget)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_40.addWidget(self.label_47)
        self.deadlineDateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.deadlineDateEdit.setStyleSheet("QDateEdit{\n"
"    background-color: rgb(11, 100, 197);\n"
"    color: white;\n"
"    font: 600 12pt \"Segoe UI\";\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"    padding:2px;\n"
"}\n"
"QDateEdit::up-button{\n"
"    background:transparent;\n"
"}\n"
"QDateEdit::down-button{\n"
"    background:transparent;\n"
"}")
        self.deadlineDateEdit.setObjectName("deadlineDateEdit")
        self.horizontalLayout_40.addWidget(self.deadlineDateEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_48 = QtWidgets.QLabel(parent=self.widget)
        self.label_48.setStyleSheet("")
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_41.addWidget(self.label_48)
        self.scholarshipFilepathTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.scholarshipFilepathTxt.setObjectName("scholarshipFilepathTxt")
        self.horizontalLayout_41.addWidget(self.scholarshipFilepathTxt)
        self.browseBtn = QtWidgets.QPushButton(parent=self.widget)
        self.browseBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.browseBtn.setStyleSheet("border:none;\n"
"border-radius:5px;\n"
"font: 600 9pt \"Segoe UI\";\n"
"margin:0px;\n"
"padding:2px;\n"
"background-color: rgb(11, 100, 197);\n"
"color:rgb(1, 14, 27);")
        self.browseBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.browseBtn.setIcon(icon)
        self.browseBtn.setObjectName("browseBtn")
        self.horizontalLayout_41.addWidget(self.browseBtn)
        self.verticalLayout_20.addLayout(self.horizontalLayout_41)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.gridLayout_3.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.widget)
        self.line.setStyleSheet("color: rgb(1, 14, 27);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.widget)
        self.line_2.setStyleSheet("color: rgb(1, 14, 27);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 6, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, 40, 20, 40)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_49 = QtWidgets.QLabel(parent=self.widget)
        self.label_49.setStyleSheet("margin-bottom:20px;")
        self.label_49.setObjectName("label_49")
        self.verticalLayout_3.addWidget(self.label_49)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_50 = QtWidgets.QLabel(parent=self.widget)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_42.addWidget(self.label_50)
        self.financialCombo = QtWidgets.QComboBox(parent=self.widget)
        self.financialCombo.setStyleSheet("QComboBox{\n"
"    border:none;\n"
"    border-bottom:1px solid white;\n"
"    background-color: rgb(11, 100, 197);\n"
"    background:transparent;\n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"")
        self.financialCombo.setObjectName("financialCombo")
        self.financialCombo.addItem("")
        self.financialCombo.addItem("")
        self.financialCombo.addItem("")
        self.financialCombo.addItem("")
        self.horizontalLayout_42.addWidget(self.financialCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_42)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.jobOrppotunitiesCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.jobOrppotunitiesCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.jobOrppotunitiesCheckBox.setText("")
        self.jobOrppotunitiesCheckBox.setObjectName("jobOrppotunitiesCheckBox")
        self.horizontalLayout.addWidget(self.jobOrppotunitiesCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.AccomodationCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.AccomodationCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.AccomodationCheckBox.setText("")
        self.AccomodationCheckBox.setObjectName("AccomodationCheckBox")
        self.horizontalLayout_2.addWidget(self.AccomodationCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.insuranceCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.insuranceCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.insuranceCheckBox.setText("")
        self.insuranceCheckBox.setObjectName("insuranceCheckBox")
        self.horizontalLayout_3.addWidget(self.insuranceCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.travelAllawanceCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.travelAllawanceCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.travelAllawanceCheckBox.setText("")
        self.travelAllawanceCheckBox.setObjectName("travelAllawanceCheckBox")
        self.horizontalLayout_4.addWidget(self.travelAllawanceCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.wrkShopCheckBox = QtWidgets.QCheckBox(parent=self.widget)
        self.wrkShopCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.wrkShopCheckBox.setText("")
        self.wrkShopCheckBox.setObjectName("wrkShopCheckBox")
        self.horizontalLayout_5.addWidget(self.wrkShopCheckBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.widget)
        self.line_3.setStyleSheet("color: rgb(1, 14, 27);")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setStyleSheet("font: 600 14pt \"Segoe UI\";\n"
"margin-bottom:30px;")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(20, -1, 20, 40)
        self.verticalLayout_31.setSpacing(15)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_51 = QtWidgets.QLabel(parent=self.widget)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_31.addWidget(self.label_51)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setContentsMargins(0, 10, 0, 30)
        self.verticalLayout_24.setSpacing(15)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_52 = QtWidgets.QLabel(parent=self.widget)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_43.addWidget(self.label_52)
        self.linkTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.linkTxt.setObjectName("linkTxt")
        self.horizontalLayout_43.addWidget(self.linkTxt)
        self.verticalLayout_24.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_53 = QtWidgets.QLabel(parent=self.widget)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_44.addWidget(self.label_53)
        self.providerEmailTxt = QtWidgets.QLineEdit(parent=self.widget)
        self.providerEmailTxt.setObjectName("providerEmailTxt")
        self.horizontalLayout_44.addWidget(self.providerEmailTxt)
        self.verticalLayout_24.addLayout(self.horizontalLayout_44)
        self.verticalLayout_31.addLayout(self.verticalLayout_24)
        self.gridLayout_3.addLayout(self.verticalLayout_31, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.uploadBtn.setText(_translate("Dialog", "UPLOAD"))
        self.cancelBtn.setText(_translate("Dialog", "CANCEL"))
        self.label_41.setText(_translate("Dialog", "SCHOLARSHIP DETAILS"))
        self.label_42.setText(_translate("Dialog", "Scholarship Name:"))
        self.label_43.setText(_translate("Dialog", "Provider:                 "))
        self.label_44.setText(_translate("Dialog", "Type:"))
        self.typeCombo.setItemText(0, _translate("Dialog", "Agriculture/Environment"))
        self.typeCombo.setItemText(1, _translate("Dialog", "Artistic/Creative"))
        self.typeCombo.setItemText(2, _translate("Dialog", "Athletic"))
        self.typeCombo.setItemText(3, _translate("Dialog", "Business/Entrepreneurship"))
        self.typeCombo.setItemText(4, _translate("Dialog", "Community service"))
        self.typeCombo.setItemText(5, _translate("Dialog", "Corporate"))
        self.typeCombo.setItemText(6, _translate("Dialog", "Disability"))
        self.typeCombo.setItemText(7, _translate("Dialog", "First-generation"))
        self.typeCombo.setItemText(8, _translate("Dialog", "Government"))
        self.typeCombo.setItemText(9, _translate("Dialog", "International student"))
        self.typeCombo.setItemText(10, _translate("Dialog", "Medical/Nursing"))
        self.typeCombo.setItemText(11, _translate("Dialog", "Merit-based"))
        self.typeCombo.setItemText(12, _translate("Dialog", "Minority"))
        self.typeCombo.setItemText(13, _translate("Dialog", "NGO/Foundation"))
        self.typeCombo.setItemText(14, _translate("Dialog", "Need-based"))
        self.typeCombo.setItemText(15, _translate("Dialog", "Religious"))
        self.typeCombo.setItemText(16, _translate("Dialog", "STEM"))
        self.typeCombo.setItemText(17, _translate("Dialog", "Teacher education"))
        self.typeCombo.setItemText(18, _translate("Dialog", "University-specific"))
        self.typeCombo.setItemText(19, _translate("Dialog", "Women in STEM"))
        self.label_45.setText(_translate("Dialog", "Subject:                   "))
        self.label_46.setText(_translate("Dialog", "Description:           "))
        self.label_47.setText(_translate("Dialog", "Deadline:               "))
        self.label_48.setText(_translate("Dialog", "File Path:               "))
        self.label_49.setText(_translate("Dialog", "SCHOLARSHIP BENEFITS"))
        self.label_50.setText(_translate("Dialog", "financial Amount:"))
        self.financialCombo.setItemText(0, _translate("Dialog", "Full Tuition"))
        self.financialCombo.setItemText(1, _translate("Dialog", "Partial"))
        self.financialCombo.setItemText(2, _translate("Dialog", "Stipend"))
        self.financialCombo.setItemText(3, _translate("Dialog", "Lump Sum"))
        self.label.setText(_translate("Dialog", "Job Opportunities"))
        self.label_2.setText(_translate("Dialog", "Accomodation"))
        self.label_3.setText(_translate("Dialog", "Insurance"))
        self.label_4.setText(_translate("Dialog", "Travel Allawance"))
        self.label_6.setText(_translate("Dialog", "Workshop Access"))
        self.label_5.setText(_translate("Dialog", "Enter Required Details"))
        self.label_51.setText(_translate("Dialog", "CONTACT INFORMATION"))
        self.label_52.setText(_translate("Dialog", "Application Link:     "))
        self.label_53.setText(_translate("Dialog", "Provider Email:        "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
