# Form implementation generated from reading ui file 'welcomePage.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import myProjectResources

class Ui_WelcomePage(object):
    def setupUi(self, WelcomePage):
        WelcomePage.setObjectName("WelcomePage")
        WelcomePage.resize(756, 625)
        WelcomePage.setMinimumSize(QtCore.QSize(756, 625))
        WelcomePage.setMaximumSize(QtCore.QSize(756, 625))
        WelcomePage.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(11, 100, 197);\n"
"    font: 600 12pt \"Segoe UI\";\n"
"    width:110px;\n"
"    padding:22px;\n"
"\n"
"}\n"
"\n"
"QGroupBox{\n"
"    \n"
"    font: 600 18pt \"Segoe UI\";\n"
"    margin-top:40px;\n"
"    margin-bottom:40px;\n"
"    margin-left:20px;\n"
"    margin-right:20px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(WelcomePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=WelcomePage)
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, -1, 20, 30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 20, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setStyleSheet("margin-left:10px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.goToAdminRegBtn = QtWidgets.QPushButton(parent=self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/adminIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.goToAdminRegBtn.setIcon(icon)
        self.goToAdminRegBtn.setObjectName("goToAdminRegBtn")
        self.horizontalLayout_3.addWidget(self.goToAdminRegBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.goToApplicantRegBtn = QtWidgets.QPushButton(parent=self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/applicantIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.goToApplicantRegBtn.setIcon(icon1)
        self.goToApplicantRegBtn.setObjectName("goToApplicantRegBtn")
        self.horizontalLayout_3.addWidget(self.goToApplicantRegBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(170, -1, 220, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.goToLoginBtn = QtWidgets.QPushButton(parent=self.groupBox)
        self.goToLoginBtn.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"background-color: rgb(20, 41, 63);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"width:10px;\n"
"padding:0px;")
        self.goToLoginBtn.setObjectName("goToLoginBtn")
        self.horizontalLayout.addWidget(self.goToLoginBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(WelcomePage)
        QtCore.QMetaObject.connectSlotsByName(WelcomePage)

    def retranslateUi(self, WelcomePage):
        _translate = QtCore.QCoreApplication.translate
        WelcomePage.setWindowTitle(_translate("WelcomePage", "Form"))
        self.groupBox.setTitle(_translate("WelcomePage", "SCHOLARSHIP MANAGEMENT SYSTEM"))
        self.label.setText(_translate("WelcomePage", "Start your journey today!"))
        self.label_2.setText(_translate("WelcomePage", "Whether you’re managing scholarships as an Admin or applying as an Applicant,"))
        self.label_3.setText(_translate("WelcomePage", "we’ve got you covered."))
        self.label_4.setText(_translate("WelcomePage", "Choose whether to register as an Admin or Applicant below:"))
        self.goToAdminRegBtn.setText(_translate("WelcomePage", "ADMIN"))
        self.goToApplicantRegBtn.setText(_translate("WelcomePage", "APPLICANT"))
        self.label_5.setText(_translate("WelcomePage", "Already have an account?"))
        self.goToLoginBtn.setText(_translate("WelcomePage", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomePage = QtWidgets.QWidget()
    ui = Ui_WelcomePage()
    ui.setupUi(WelcomePage)
    WelcomePage.show()
    sys.exit(app.exec())
