# Form implementation generated from reading ui file 'applyScholarship.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_applyScholarshipForm(object):
    def setupUi(self, applyScholarshipForm):
        applyScholarshipForm.setObjectName("applyScholarshipForm")
        applyScholarshipForm.resize(520, 518)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(applyScholarshipForm.sizePolicy().hasHeightForWidth())
        applyScholarshipForm.setSizePolicy(sizePolicy)
        applyScholarshipForm.setMinimumSize(QtCore.QSize(520, 518))
        applyScholarshipForm.setMaximumSize(QtCore.QSize(520, 518))
        applyScholarshipForm.setStyleSheet("QWidget{\n"
"    \n"
"    \n"
"    background-color: rgb(11, 100, 197);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding-top:10px;\n"
"    padding-bottom:10px;\n"
"    padding-right:40px;\n"
"    padding-left:40px;\n"
"    border: 1px solid;\n"
"    border-radius:10px;\n"
"    margin-bottom: 30px;\n"
"    background-color: rgb(1, 14, 27);\n"
"    font: 600 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    background-color: rgb(11, 100, 197);\n"
"    border-bottom: 1px solid white;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"}\n"
"\n"
"QRadioButton{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(applyScholarshipForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=applyScholarshipForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 488, 784))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setStyleSheet("font: 600 14pt \"Segoe UI\";\n"
"margin-bottom:30px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.formerSchoolTxt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formerSchoolTxt.sizePolicy().hasHeightForWidth())
        self.formerSchoolTxt.setSizePolicy(sizePolicy)
        self.formerSchoolTxt.setObjectName("formerSchoolTxt")
        self.horizontalLayout_2.addWidget(self.formerSchoolTxt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.gpaSpinbox = QtWidgets.QSpinBox(parent=self.scrollAreaWidgetContents)
        self.gpaSpinbox.setMaximum(5)
        self.gpaSpinbox.setObjectName("gpaSpinbox")
        self.horizontalLayout_3.addWidget(self.gpaSpinbox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.line_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.yesRadioBtn = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.yesRadioBtn.setObjectName("yesRadioBtn")
        self.horizontalLayout_4.addWidget(self.yesRadioBtn)
        self.noRadioBtn = QtWidgets.QRadioButton(parent=self.scrollAreaWidgetContents)
        self.noRadioBtn.setObjectName("noRadioBtn")
        self.horizontalLayout_4.addWidget(self.noRadioBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.reasonForApplyingTxt = QtWidgets.QTextEdit(parent=self.scrollAreaWidgetContents)
        self.reasonForApplyingTxt.setStyleSheet("heigth:81px;\n"
"background-color:white;\n"
"border: 1px solid black;\n"
"border-radius: 7px;\n"
"color:black;\n"
"font: 11pt \"Segoe UI\";")
        self.reasonForApplyingTxt.setObjectName("reasonForApplyingTxt")
        self.verticalLayout_5.addWidget(self.reasonForApplyingTxt)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.careerGoalsTxt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.careerGoalsTxt.setObjectName("careerGoalsTxt")
        self.horizontalLayout_5.addWidget(self.careerGoalsTxt)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.transcriptTxt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.transcriptTxt.setObjectName("transcriptTxt")
        self.horizontalLayout_6.addWidget(self.transcriptTxt)
        self.transcriptBrowseBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.transcriptBrowseBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.transcriptBrowseBtn.setStyleSheet("border:none;\n"
"border-radius:5px;\n"
"font: 600 9pt \"Segoe UI\";\n"
"margin:0px;\n"
"padding:2px;\n"
"background-color: rgb(11, 100, 197);\n"
"color:rgb(1, 14, 27);")
        self.transcriptBrowseBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.transcriptBrowseBtn.setIcon(icon)
        self.transcriptBrowseBtn.setObjectName("transcriptBrowseBtn")
        self.horizontalLayout_6.addWidget(self.transcriptBrowseBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.nationalIdTxt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.nationalIdTxt.setObjectName("nationalIdTxt")
        self.horizontalLayout_7.addWidget(self.nationalIdTxt)
        self.nationalBrowseBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.nationalBrowseBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.nationalBrowseBtn.setStyleSheet("border:none;\n"
"border-radius:5px;\n"
"font: 600 9pt \"Segoe UI\";\n"
"margin:0px;\n"
"padding:2px;\n"
"background-color: rgb(11, 100, 197);\n"
"color:rgb(1, 14, 27);")
        self.nationalBrowseBtn.setText("")
        self.nationalBrowseBtn.setIcon(icon)
        self.nationalBrowseBtn.setObjectName("nationalBrowseBtn")
        self.horizontalLayout_7.addWidget(self.nationalBrowseBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.recommedationLetterTxt = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        self.recommedationLetterTxt.setObjectName("recommedationLetterTxt")
        self.horizontalLayout_8.addWidget(self.recommedationLetterTxt)
        self.recommBrowseBtn = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        self.recommBrowseBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.recommBrowseBtn.setStyleSheet("border:none;\n"
"border-radius:5px;\n"
"font: 600 9pt \"Segoe UI\";\n"
"margin:0px;\n"
"padding:2px;\n"
"background-color: rgb(11, 100, 197);\n"
"color:rgb(1, 14, 27);")
        self.recommBrowseBtn.setText("")
        self.recommBrowseBtn.setIcon(icon)
        self.recommBrowseBtn.setObjectName("recommBrowseBtn")
        self.horizontalLayout_8.addWidget(self.recommBrowseBtn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.line_4 = QtWidgets.QFrame(parent=applyScholarshipForm)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 19, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyBtn = QtWidgets.QPushButton(parent=applyScholarshipForm)
        self.applyBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.applyBtn.setStyleSheet("background-color: rgb(1, 14, 27);")
        self.applyBtn.setObjectName("applyBtn")
        self.horizontalLayout.addWidget(self.applyBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(parent=applyScholarshipForm)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setStyleSheet("background-color: rgb(1, 14, 27);")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(applyScholarshipForm)
        QtCore.QMetaObject.connectSlotsByName(applyScholarshipForm)

    def retranslateUi(self, applyScholarshipForm):
        _translate = QtCore.QCoreApplication.translate
        applyScholarshipForm.setWindowTitle(_translate("applyScholarshipForm", "Form"))
        self.label.setText(_translate("applyScholarshipForm", "Enter Required Details"))
        self.label_2.setText(_translate("applyScholarshipForm", "ACADEMIC INFORMATION"))
        self.label_3.setText(_translate("applyScholarshipForm", "Fromer School Attended        "))
        self.formerSchoolTxt.setPlaceholderText(_translate("applyScholarshipForm", "e.g. University of Greenwich"))
        self.label_4.setText(_translate("applyScholarshipForm", "GPA"))
        self.label_5.setText(_translate("applyScholarshipForm", "FINANCIAL INFORMATION"))
        self.label_6.setText(_translate("applyScholarshipForm", "Do you require financial assestance?"))
        self.yesRadioBtn.setText(_translate("applyScholarshipForm", "Yes"))
        self.noRadioBtn.setText(_translate("applyScholarshipForm", "No"))
        self.label_7.setText(_translate("applyScholarshipForm", "MOTIVATION"))
        self.label_8.setText(_translate("applyScholarshipForm", "Why are you applying to this scholarship?"))
        self.label_9.setText(_translate("applyScholarshipForm", "Career Goals                     "))
        self.careerGoalsTxt.setPlaceholderText(_translate("applyScholarshipForm", "Optional"))
        self.label_10.setText(_translate("applyScholarshipForm", "Documents"))
        self.label_11.setText(_translate("applyScholarshipForm", "Transcript                         "))
        self.label_12.setText(_translate("applyScholarshipForm", "National ID                      "))
        self.label_13.setText(_translate("applyScholarshipForm", "Recommendation letter  "))
        self.applyBtn.setText(_translate("applyScholarshipForm", "APPLY"))
        self.cancelBtn.setText(_translate("applyScholarshipForm", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    applyScholarshipForm = QtWidgets.QWidget()
    ui = Ui_applyScholarshipForm()
    ui.setupUi(applyScholarshipForm)
    applyScholarshipForm.show()
    sys.exit(app.exec())
