# Form implementation generated from reading ui file 'viewApplications.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewApplicantForm(object):
    def setupUi(self, ViewApplicantForm):
        ViewApplicantForm.setObjectName("ViewApplicantForm")
        ViewApplicantForm.resize(561, 628)
        ViewApplicantForm.setMinimumSize(QtCore.QSize(561, 628))
        ViewApplicantForm.setMaximumSize(QtCore.QSize(561, 16777215))
        ViewApplicantForm.setStyleSheet("QWidget{\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 7px;\n"
"    \n"
"    font: 600 11pt \"Segoe UI\";\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(ViewApplicantForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=ViewApplicantForm)
        self.label_4.setStyleSheet("margin-top:30px;\n"
"margin-bottom:30px;\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.scrollArea = QtWidgets.QScrollArea(parent=ViewApplicantForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 684))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.applicanNameLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.applicanNameLabel.setObjectName("applicanNameLabel")
        self.verticalLayout_5.addWidget(self.applicanNameLabel)
        self.scholarshipNameLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.scholarshipNameLabel.setObjectName("scholarshipNameLabel")
        self.verticalLayout_5.addWidget(self.scholarshipNameLabel)
        self.incomeBracketLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.incomeBracketLabel.setObjectName("incomeBracketLabel")
        self.verticalLayout_5.addWidget(self.incomeBracketLabel)
        self.dateSubmittedLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.dateSubmittedLabel.setObjectName("dateSubmittedLabel")
        self.verticalLayout_5.addWidget(self.dateSubmittedLabel)
        self.applicationStatusLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.applicationStatusLabel.setObjectName("applicationStatusLabel")
        self.verticalLayout_5.addWidget(self.applicationStatusLabel)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.reasonForApplyingWidget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.reasonForApplyingWidget.setStyleSheet("border-radius:7px;\n"
"background-color: rgb(20, 41, 63);\n"
"color: rgb(255, 255, 255);")
        self.reasonForApplyingWidget.setObjectName("reasonForApplyingWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.reasonForApplyingWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.reasonForApplyingScrollArea = QtWidgets.QScrollArea(parent=self.reasonForApplyingWidget)
        self.reasonForApplyingScrollArea.setStyleSheet("")
        self.reasonForApplyingScrollArea.setWidgetResizable(True)
        self.reasonForApplyingScrollArea.setObjectName("reasonForApplyingScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 491, 54))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.reasonForApplicationLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_2)
        self.reasonForApplicationLabel.setWordWrap(True)
        self.reasonForApplicationLabel.setObjectName("reasonForApplicationLabel")
        self.gridLayout_2.addWidget(self.reasonForApplicationLabel, 0, 0, 1, 1)
        self.reasonForApplyingScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.reasonForApplyingScrollArea)
        self.verticalLayout_2.addWidget(self.reasonForApplyingWidget)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.line_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_10.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.viewDocsTableWidget = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.viewDocsTableWidget.setStyleSheet("border:1px solid black;\n"
"border-radius:7px;")
        self.viewDocsTableWidget.setObjectName("viewDocsTableWidget")
        self.viewDocsTableWidget.setColumnCount(0)
        self.viewDocsTableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.viewDocsTableWidget)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.documentsUploadedLabel = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.documentsUploadedLabel.setStyleSheet("margin-bottom:30px;")
        self.documentsUploadedLabel.setWordWrap(True)
        self.documentsUploadedLabel.setObjectName("documentsUploadedLabel")
        self.verticalLayout_10.addWidget(self.documentsUploadedLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.line_5 = QtWidgets.QFrame(parent=ViewApplicantForm)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelBtn = QtWidgets.QPushButton(parent=ViewApplicantForm)
        self.cancelBtn.setStyleSheet("background-color: rgb(1, 14, 27);")
        self.cancelBtn.setObjectName("cancelBtn")
        self.gridLayout.addWidget(self.cancelBtn, 1, 0, 1, 2)
        self.acceptBtn = QtWidgets.QPushButton(parent=ViewApplicantForm)
        self.acceptBtn.setStyleSheet("color: rgb(55, 244, 32);\n"
"background-color: rgb(1, 14, 27);")
        self.acceptBtn.setObjectName("acceptBtn")
        self.gridLayout.addWidget(self.acceptBtn, 0, 0, 1, 1)
        self.rejectBtn = QtWidgets.QPushButton(parent=ViewApplicantForm)
        self.rejectBtn.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(1, 14, 27);")
        self.rejectBtn.setObjectName("rejectBtn")
        self.gridLayout.addWidget(self.rejectBtn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(ViewApplicantForm)
        QtCore.QMetaObject.connectSlotsByName(ViewApplicantForm)

    def retranslateUi(self, ViewApplicantForm):
        _translate = QtCore.QCoreApplication.translate
        ViewApplicantForm.setWindowTitle(_translate("ViewApplicantForm", "Form"))
        self.label_4.setText(_translate("ViewApplicantForm", "APPLICATION DETIALS"))
        self.applicanNameLabel.setText(_translate("ViewApplicantForm", "Applicant Name:"))
        self.scholarshipNameLabel.setText(_translate("ViewApplicantForm", "Scholarship Name:"))
        self.incomeBracketLabel.setText(_translate("ViewApplicantForm", "Income Bracket"))
        self.dateSubmittedLabel.setText(_translate("ViewApplicantForm", "Application Submittted before/after:"))
        self.applicationStatusLabel.setText(_translate("ViewApplicantForm", "Application Status:"))
        self.label_7.setText(_translate("ViewApplicantForm", "Reason for applying"))
        self.reasonForApplicationLabel.setText(_translate("ViewApplicantForm", "NO DATA TO DISPLAY"))
        self.label_9.setText(_translate("ViewApplicantForm", "Uploaded Docs"))
        self.documentsUploadedLabel.setText(_translate("ViewApplicantForm", "Documents uploaded: uploaded docs/required docs"))
        self.cancelBtn.setText(_translate("ViewApplicantForm", "CANCEL"))
        self.acceptBtn.setText(_translate("ViewApplicantForm", "ACCECPT"))
        self.rejectBtn.setText(_translate("ViewApplicantForm", "REJECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewApplicantForm = QtWidgets.QWidget()
    ui = Ui_ViewApplicantForm()
    ui.setupUi(ViewApplicantForm)
    ViewApplicantForm.show()
    sys.exit(app.exec())
