# Form implementation generated from reading ui file 'schemeDisplay.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(477, 598)
        Form.setMinimumSize(QtCore.QSize(477, 598))
        Form.setMaximumSize(QtCore.QSize(477, 598))
        Form.setStyleSheet("QWidget{\n"
"    font: 600 12pt \"Segoe UI\";\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(1, 14, 27);\n"
"    padding:10px;\n"
"}\n"
"")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setStyleSheet("font: 600 14pt \"Segoe UI\";\n"
"margin-top:20px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 40)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.schemeNameLabel = QtWidgets.QLabel(parent=Form)
        self.schemeNameLabel.setObjectName("schemeNameLabel")
        self.verticalLayout_3.addWidget(self.schemeNameLabel)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.schemeDescriptionLabel = QtWidgets.QLabel(parent=Form)
        self.schemeDescriptionLabel.setWordWrap(True)
        self.schemeDescriptionLabel.setObjectName("schemeDescriptionLabel")
        self.verticalLayout.addWidget(self.schemeDescriptionLabel)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(parent=Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.benefitDetailsLabel = QtWidgets.QLabel(parent=Form)
        self.benefitDetailsLabel.setWordWrap(True)
        self.benefitDetailsLabel.setObjectName("benefitDetailsLabel")
        self.verticalLayout_2.addWidget(self.benefitDetailsLabel)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.line_4 = QtWidgets.QFrame(parent=Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.cancelBtn = QtWidgets.QPushButton(parent=Form)
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalLayout_4.addWidget(self.cancelBtn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "SCHEME DETAILS"))
        self.schemeNameLabel.setText(_translate("Form", "SCHEME NAME: None"))
        self.label_3.setText(_translate("Form", "SCHEME DESCRIPTION"))
        self.schemeDescriptionLabel.setText(_translate("Form", "No description"))
        self.label_4.setText(_translate("Form", "BENEFIT DETAILS"))
        self.benefitDetailsLabel.setText(_translate("Form", "No benefits"))
        self.cancelBtn.setText(_translate("Form", "CANCEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
