# Form implementation generated from reading ui file 'dialogTemplate.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_templateDialog(object):
    def setupUi(self, templateDialog):
        templateDialog.setObjectName("templateDialog")
        templateDialog.resize(286, 129)
        templateDialog.setMinimumSize(QtCore.QSize(286, 129))
        templateDialog.setMaximumSize(QtCore.QSize(286, 129))
        templateDialog.setStyleSheet("QDialog{\n"
"    background-color: rgb(6, 57, 112);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 12pt \"Segoe UI\";\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(templateDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.dialogTextLabel = QtWidgets.QLabel(parent=templateDialog)
        self.dialogTextLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dialogTextLabel.setWordWrap(True)
        self.dialogTextLabel.setObjectName("dialogTextLabel")
        self.verticalLayout.addWidget(self.dialogTextLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.okCanelBtnBox = QtWidgets.QDialogButtonBox(parent=templateDialog)
        self.okCanelBtnBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.okCanelBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.okCanelBtnBox.setCenterButtons(True)
        self.okCanelBtnBox.setObjectName("okCanelBtnBox")
        self.verticalLayout.addWidget(self.okCanelBtnBox)

        self.retranslateUi(templateDialog)
        self.okCanelBtnBox.accepted.connect(templateDialog.accept) # type: ignore
        self.okCanelBtnBox.rejected.connect(templateDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(templateDialog)

    def retranslateUi(self, templateDialog):
        _translate = QtCore.QCoreApplication.translate
        templateDialog.setWindowTitle(_translate("templateDialog", "Dialog"))
        self.dialogTextLabel.setText(_translate("templateDialog", "Dialoag Text..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    templateDialog = QtWidgets.QDialog()
    ui = Ui_templateDialog()
    ui.setupUi(templateDialog)
    templateDialog.show()
    sys.exit(app.exec())
