# Form implementation generated from reading ui file 'applicantRegistration.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import myProjectResources

class Ui_applicantRegistration(object):
    def setupUi(self, applicantRegistration):
        applicantRegistration.setObjectName("applicantRegistration")
        applicantRegistration.resize(619, 766)
        applicantRegistration.setMinimumSize(QtCore.QSize(596, 596))
        applicantRegistration.setMaximumSize(QtCore.QSize(620, 800))
        applicantRegistration.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(applicantRegistration)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=applicantRegistration)
        self.label.setStyleSheet("margin-top:20px;\n"
"font: 700 16pt \"Segoe UI\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 40, 20, 40)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.nameTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.nameTxt.setObjectName("nameTxt")
        self.horizontalLayout.addWidget(self.nameTxt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.emailTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.emailTxt.setObjectName("emailTxt")
        self.horizontalLayout_2.addWidget(self.emailTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.nationalityTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.nationalityTxt.setObjectName("nationalityTxt")
        self.horizontalLayout_4.addWidget(self.nationalityTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.phoneNumTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.phoneNumTxt.setObjectName("phoneNumTxt")
        self.horizontalLayout_10.addWidget(self.phoneNumTxt)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.ageSpinBox = QtWidgets.QSpinBox(parent=applicantRegistration)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.horizontalLayout_9.addWidget(self.ageSpinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.genderCombo = QtWidgets.QComboBox(parent=applicantRegistration)
        self.genderCombo.setStyleSheet("padding:7px;\n"
"font: 11pt \"Segoe UI\";\n"
"")
        self.genderCombo.setEditable(False)
        self.genderCombo.setCurrentText("")
        self.genderCombo.setObjectName("genderCombo")
        self.horizontalLayout_11.addWidget(self.genderCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.DOBdateEdit = QtWidgets.QDateEdit(parent=applicantRegistration)
        self.DOBdateEdit.setStyleSheet("padding:7px;\n"
"font: 11pt \"Segoe UI\";\n"
"")
        self.DOBdateEdit.setObjectName("DOBdateEdit")
        self.horizontalLayout_3.addWidget(self.DOBdateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.educationCombo = QtWidgets.QComboBox(parent=applicantRegistration)
        self.educationCombo.setStyleSheet("padding:7px;\n"
"font: 11pt \"Segoe UI\";\n"
"")
        self.educationCombo.setEditable(False)
        self.educationCombo.setCurrentText("")
        self.educationCombo.setObjectName("educationCombo")
        self.horizontalLayout_5.addWidget(self.educationCombo)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.passTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.passTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passTxt.setObjectName("passTxt")
        self.horizontalLayout_6.addWidget(self.passTxt)
        self.showHidePassBtn = QtWidgets.QPushButton(parent=applicantRegistration)
        self.showHidePassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.showHidePassBtn.setStyleSheet("border:none;\n"
"margin-top:7px;")
        self.showHidePassBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/seeWhiteIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showHidePassBtn.setIcon(icon)
        self.showHidePassBtn.setIconSize(QtCore.QSize(20, 20))
        self.showHidePassBtn.setObjectName("showHidePassBtn")
        self.horizontalLayout_6.addWidget(self.showHidePassBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.confirmPassTxt = QtWidgets.QLineEdit(parent=applicantRegistration)
        self.confirmPassTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.confirmPassTxt.setObjectName("confirmPassTxt")
        self.horizontalLayout_7.addWidget(self.confirmPassTxt)
        self.showHideConfirmPassBtn = QtWidgets.QPushButton(parent=applicantRegistration)
        self.showHideConfirmPassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.showHideConfirmPassBtn.setStyleSheet("border:none;\n"
"margin-top:7px;")
        self.showHideConfirmPassBtn.setText("")
        self.showHideConfirmPassBtn.setIcon(icon)
        self.showHideConfirmPassBtn.setIconSize(QtCore.QSize(20, 20))
        self.showHideConfirmPassBtn.setObjectName("showHideConfirmPassBtn")
        self.horizontalLayout_7.addWidget(self.showHideConfirmPassBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.errorMsgLog = QtWidgets.QLabel(parent=applicantRegistration)
        self.errorMsgLog.setStyleSheet("color:Red;\n"
"margin-left:15px;\n"
"margin-right:15px;\n"
"margin-top:15px;")
        self.errorMsgLog.setObjectName("errorMsgLog")
        self.verticalLayout_2.addWidget(self.errorMsgLog)
        spacerItem = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.signUpBtn = QtWidgets.QPushButton(parent=applicantRegistration)
        self.signUpBtn.setStyleSheet("background-color: rgb(11, 100, 197);\n"
"font: 600 12pt \"Segoe UI\";\n"
"padding:15px;\n"
"margin-left: 20px;\n"
"margin-right: 20px;")
        self.signUpBtn.setObjectName("signUpBtn")
        self.verticalLayout_2.addWidget(self.signUpBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(145, -1, 200, 20)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=applicantRegistration)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.goToLoginPageBtn = QtWidgets.QPushButton(parent=applicantRegistration)
        self.goToLoginPageBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.goToLoginPageBtn.setStyleSheet("border:none;\n"
"font: 600 12pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"")
        self.goToLoginPageBtn.setCheckable(True)
        self.goToLoginPageBtn.setObjectName("goToLoginPageBtn")
        self.horizontalLayout_8.addWidget(self.goToLoginPageBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)

        self.retranslateUi(applicantRegistration)
        QtCore.QMetaObject.connectSlotsByName(applicantRegistration)

    def retranslateUi(self, applicantRegistration):
        _translate = QtCore.QCoreApplication.translate
        applicantRegistration.setWindowTitle(_translate("applicantRegistration", "Form"))
        self.label.setText(_translate("applicantRegistration", "SIGN UP"))
        self.label_2.setText(_translate("applicantRegistration", "Full Name:              "))
        self.label_3.setText(_translate("applicantRegistration", "Email:                     "))
        self.label_5.setText(_translate("applicantRegistration", "Nationality:            "))
        self.label_11.setText(_translate("applicantRegistration", "Phone Number     "))
        self.label_10.setText(_translate("applicantRegistration", "Age"))
        self.label_12.setText(_translate("applicantRegistration", "Gender"))
        self.genderCombo.setPlaceholderText(_translate("applicantRegistration", "Please Select From the List"))
        self.label_4.setText(_translate("applicantRegistration", "Date of Birth:"))
        self.label_6.setText(_translate("applicantRegistration", "Education Level:"))
        self.educationCombo.setPlaceholderText(_translate("applicantRegistration", "Please Select From the List"))
        self.label_7.setText(_translate("applicantRegistration", "Password:              "))
        self.label_8.setText(_translate("applicantRegistration", "Confirm Password:"))
        self.errorMsgLog.setText(_translate("applicantRegistration", "Error Msg Here...."))
        self.signUpBtn.setText(_translate("applicantRegistration", "SIGN UP"))
        self.label_9.setText(_translate("applicantRegistration", "Already have an account?"))
        self.goToLoginPageBtn.setText(_translate("applicantRegistration", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    applicantRegistration = QtWidgets.QWidget()
    ui = Ui_applicantRegistration()
    ui.setupUi(applicantRegistration)
    applicantRegistration.show()
    sys.exit(app.exec())
