# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import myProjectResources


class Ui_loginPage(object):
    def setupUi(self, loginPage):
        loginPage.setObjectName("loginPage")
        loginPage.resize(602, 364)
        loginPage.setStyleSheet("QWidget{\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"    border: none;\n"
"    border-bottom: 1px solid white;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(loginPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(parent=loginPage)
        self.label_8.setStyleSheet("margin-top:10px;\n"
"font: 700 16pt \"Segoe UI\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=loginPage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.loginEmailTxt = QtWidgets.QLineEdit(parent=loginPage)
        self.loginEmailTxt.setStyleSheet("margin-right:42px;")
        self.loginEmailTxt.setObjectName("loginEmailTxt")
        self.horizontalLayout.addWidget(self.loginEmailTxt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=loginPage)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.loginPassTxt = QtWidgets.QLineEdit(parent=loginPage)
        self.loginPassTxt.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.loginPassTxt.setObjectName("loginPassTxt")
        self.horizontalLayout_6.addWidget(self.loginPassTxt)
        self.loginShowHidePassBtn = QtWidgets.QPushButton(parent=loginPage)
        self.loginShowHidePassBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.loginShowHidePassBtn.setStyleSheet("border:none;\n"
"padding:5px;")
        self.loginShowHidePassBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/seeWhiteIcon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.loginShowHidePassBtn.setIcon(icon)
        self.loginShowHidePassBtn.setIconSize(QtCore.QSize(20, 20))
        self.loginShowHidePassBtn.setObjectName("loginShowHidePassBtn")
        self.horizontalLayout_6.addWidget(self.loginShowHidePassBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 35, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.signInBtn = QtWidgets.QPushButton(parent=loginPage)
        self.signInBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.signInBtn.setStyleSheet("background-color: rgb(11, 100, 197);\n"
"font: 600 12pt \"Segoe UI\";\n"
"padding:15px;\n"
"margin-left: 20px;\n"
"margin-right: 20px;")
        self.signInBtn.setObjectName("signInBtn")
        self.verticalLayout_3.addWidget(self.signInBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 36, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.label_7 = QtWidgets.QLabel(parent=loginPage)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.goToRegistrationPageBtn = QtWidgets.QPushButton(parent=loginPage)
        self.goToRegistrationPageBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.goToRegistrationPageBtn.setStyleSheet("border:none;\n"
"text-decoration: underline;\n"
"font: 600 10pt \"Segoe UI\";")
        self.goToRegistrationPageBtn.setObjectName("goToRegistrationPageBtn")
        self.horizontalLayout_7.addWidget(self.goToRegistrationPageBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)

        self.retranslateUi(loginPage)
        QtCore.QMetaObject.connectSlotsByName(loginPage)

    def retranslateUi(self, loginPage):
        _translate = QtCore.QCoreApplication.translate
        loginPage.setWindowTitle(_translate("loginPage", "Form"))
        self.label_8.setText(_translate("loginPage", "SIGN IN"))
        self.label.setText(_translate("loginPage", "Email             "))
        self.label_6.setText(_translate("loginPage", "Password      "))
        self.signInBtn.setText(_translate("loginPage", "SIGN IN"))
        self.label_7.setText(_translate("loginPage", "Don\'t have an account?"))
        self.goToRegistrationPageBtn.setText(_translate("loginPage", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginPage = QtWidgets.QWidget()
    ui = Ui_loginPage()
    ui.setupUi(loginPage)
    loginPage.show()
    sys.exit(app.exec())
