# Form implementation generated from reading ui file 'verifyEmail.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VerifyEmail(object):
    def setupUi(self, VerifyEmail):
        VerifyEmail.setObjectName("VerifyEmail")
        VerifyEmail.resize(484, 311)
        VerifyEmail.setMinimumSize(QtCore.QSize(484, 311))
        VerifyEmail.setMaximumSize(QtCore.QSize(484, 311))
        VerifyEmail.setStyleSheet("QWidget{\n"
"    background-color: rgb(20, 41, 63);\n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    font: 600 12pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit{\n"
"\n"
"    border: 1px solid white;\n"
"    border-radius:7px;\n"
"    padding:5px;\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(VerifyEmail)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=VerifyEmail)
        self.label_2.setStyleSheet("font: 700 16pt \"Segoe UI\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(25, 30, 25, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.codeTxt = QtWidgets.QLineEdit(parent=VerifyEmail)
        self.codeTxt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.codeTxt.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.codeTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.codeTxt.setClearButtonEnabled(True)
        self.codeTxt.setObjectName("codeTxt")
        self.horizontalLayout.addWidget(self.codeTxt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_2 = QtWidgets.QPushButton(parent=VerifyEmail)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(11, 100, 197);\n"
"font: 600 12pt \"Segoe UI\";\n"
"padding:15px;\n"
"margin-left: 20px;\n"
"margin-right: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(100, 30, 150, 30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=VerifyEmail)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(parent=VerifyEmail)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("border:none;\n"
"font: 600 12pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(VerifyEmail)
        QtCore.QMetaObject.connectSlotsByName(VerifyEmail)

    def retranslateUi(self, VerifyEmail):
        _translate = QtCore.QCoreApplication.translate
        VerifyEmail.setWindowTitle(_translate("VerifyEmail", "Form"))
        self.label_2.setText(_translate("VerifyEmail", "Enter verification Code"))
        self.pushButton_2.setText(_translate("VerifyEmail", "VERIFY"))
        self.label_3.setText(_translate("VerifyEmail", "Didn\'t Recieve Code?"))
        self.pushButton.setText(_translate("VerifyEmail", "Resend"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VerifyEmail = QtWidgets.QWidget()
    ui = Ui_VerifyEmail()
    ui.setupUi(VerifyEmail)
    VerifyEmail.show()
    sys.exit(app.exec())
